// Code generated by go-swagger; DO NOT EDIT.

package infra_object_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// APIUpdateInfraObjectsResponse api update infra objects response
// swagger:model apiUpdateInfraObjectsResponse
type APIUpdateInfraObjectsResponse struct {

	// infra objects
	InfraObjects []*APIInfraObject `json:"infra_objects"`
}

// Validate validates this api update infra objects response
func (m *APIUpdateInfraObjectsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInfraObjects(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIUpdateInfraObjectsResponse) validateInfraObjects(formats strfmt.Registry) error {

	if swag.IsZero(m.InfraObjects) { // not required
		return nil
	}

	for i := 0; i < len(m.InfraObjects); i++ {
		if swag.IsZero(m.InfraObjects[i]) { // not required
			continue
		}

		if m.InfraObjects[i] != nil {
			if err := m.InfraObjects[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("infra_objects" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIUpdateInfraObjectsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIUpdateInfraObjectsResponse) UnmarshalBinary(b []byte) error {
	var res APIUpdateInfraObjectsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
