// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: ValueType.proto

package go_client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValueType_Enum int32

const (
	ValueType_INVALID             ValueType_Enum = 0
	ValueType_BYTES               ValueType_Enum = 1
	ValueType_STRING              ValueType_Enum = 2
	ValueType_INT32               ValueType_Enum = 3
	ValueType_INT64               ValueType_Enum = 4
	ValueType_DOUBLE              ValueType_Enum = 5
	ValueType_FLOAT               ValueType_Enum = 6
	ValueType_BOOL                ValueType_Enum = 7
	ValueType_UNIX_TIMESTAMP      ValueType_Enum = 8
	ValueType_BYTES_LIST          ValueType_Enum = 11
	ValueType_STRING_LIST         ValueType_Enum = 12
	ValueType_INT32_LIST          ValueType_Enum = 13
	ValueType_INT64_LIST          ValueType_Enum = 14
	ValueType_DOUBLE_LIST         ValueType_Enum = 15
	ValueType_FLOAT_LIST          ValueType_Enum = 16
	ValueType_BOOL_LIST           ValueType_Enum = 17
	ValueType_UNIX_TIMESTAMP_LIST ValueType_Enum = 18
	ValueType_NULL                ValueType_Enum = 19
)

// Enum value maps for ValueType_Enum.
var (
	ValueType_Enum_name = map[int32]string{
		0:  "INVALID",
		1:  "BYTES",
		2:  "STRING",
		3:  "INT32",
		4:  "INT64",
		5:  "DOUBLE",
		6:  "FLOAT",
		7:  "BOOL",
		8:  "UNIX_TIMESTAMP",
		11: "BYTES_LIST",
		12: "STRING_LIST",
		13: "INT32_LIST",
		14: "INT64_LIST",
		15: "DOUBLE_LIST",
		16: "FLOAT_LIST",
		17: "BOOL_LIST",
		18: "UNIX_TIMESTAMP_LIST",
		19: "NULL",
	}
	ValueType_Enum_value = map[string]int32{
		"INVALID":             0,
		"BYTES":               1,
		"STRING":              2,
		"INT32":               3,
		"INT64":               4,
		"DOUBLE":              5,
		"FLOAT":               6,
		"BOOL":                7,
		"UNIX_TIMESTAMP":      8,
		"BYTES_LIST":          11,
		"STRING_LIST":         12,
		"INT32_LIST":          13,
		"INT64_LIST":          14,
		"DOUBLE_LIST":         15,
		"FLOAT_LIST":          16,
		"BOOL_LIST":           17,
		"UNIX_TIMESTAMP_LIST": 18,
		"NULL":                19,
	}
)

func (x ValueType_Enum) Enum() *ValueType_Enum {
	p := new(ValueType_Enum)
	*p = x
	return p
}

func (x ValueType_Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueType_Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_ValueType_proto_enumTypes[0].Descriptor()
}

func (ValueType_Enum) Type() protoreflect.EnumType {
	return &file_ValueType_proto_enumTypes[0]
}

func (x ValueType_Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueType_Enum.Descriptor instead.
func (ValueType_Enum) EnumDescriptor() ([]byte, []int) {
	return file_ValueType_proto_rawDescGZIP(), []int{0, 0}
}

type ValueType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ValueType) Reset() {
	*x = ValueType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ValueType_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValueType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueType) ProtoMessage() {}

func (x *ValueType) ProtoReflect() protoreflect.Message {
	mi := &file_ValueType_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueType.ProtoReflect.Descriptor instead.
func (*ValueType) Descriptor() ([]byte, []int) {
	return file_ValueType_proto_rawDescGZIP(), []int{0}
}

var File_ValueType_proto protoreflect.FileDescriptor

var file_ValueType_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x97, 0x02, 0x0a, 0x09, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x22, 0x89, 0x02, 0x0a, 0x04, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0b, 0x0a,
	0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x59,
	0x54, 0x45, 0x53, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10,
	0x02, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4e, 0x54, 0x33, 0x32, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05,
	0x49, 0x4e, 0x54, 0x36, 0x34, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x4f, 0x55, 0x42, 0x4c,
	0x45, 0x10, 0x05, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x10, 0x06, 0x12, 0x08,
	0x0a, 0x04, 0x42, 0x4f, 0x4f, 0x4c, 0x10, 0x07, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x4e, 0x49, 0x58,
	0x5f, 0x54, 0x49, 0x4d, 0x45, 0x53, 0x54, 0x41, 0x4d, 0x50, 0x10, 0x08, 0x12, 0x0e, 0x0a, 0x0a,
	0x42, 0x59, 0x54, 0x45, 0x53, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x0b, 0x12, 0x0f, 0x0a, 0x0b,
	0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x0c, 0x12, 0x0e, 0x0a,
	0x0a, 0x49, 0x4e, 0x54, 0x33, 0x32, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x0d, 0x12, 0x0e, 0x0a,
	0x0a, 0x49, 0x4e, 0x54, 0x36, 0x34, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x0e, 0x12, 0x0f, 0x0a,
	0x0b, 0x44, 0x4f, 0x55, 0x42, 0x4c, 0x45, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x0f, 0x12, 0x0e,
	0x0a, 0x0a, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x10, 0x12, 0x0d,
	0x0a, 0x09, 0x42, 0x4f, 0x4f, 0x4c, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x11, 0x12, 0x17, 0x0a,
	0x13, 0x55, 0x4e, 0x49, 0x58, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x53, 0x54, 0x41, 0x4d, 0x50, 0x5f,
	0x4c, 0x49, 0x53, 0x54, 0x10, 0x12, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x55, 0x4c, 0x4c, 0x10, 0x13,
	0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66,
	0x65, 0x61, 0x73, 0x74, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x66, 0x65, 0x61, 0x73, 0x74, 0x2f, 0x62,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f, 0x5f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ValueType_proto_rawDescOnce sync.Once
	file_ValueType_proto_rawDescData = file_ValueType_proto_rawDesc
)

func file_ValueType_proto_rawDescGZIP() []byte {
	file_ValueType_proto_rawDescOnce.Do(func() {
		file_ValueType_proto_rawDescData = protoimpl.X.CompressGZIP(file_ValueType_proto_rawDescData)
	})
	return file_ValueType_proto_rawDescData
}

var file_ValueType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ValueType_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ValueType_proto_goTypes = []interface{}{
	(ValueType_Enum)(0), // 0: api.ValueType.Enum
	(*ValueType)(nil),   // 1: api.ValueType
}
var file_ValueType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ValueType_proto_init() }
func file_ValueType_proto_init() {
	if File_ValueType_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ValueType_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValueType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ValueType_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ValueType_proto_goTypes,
		DependencyIndexes: file_ValueType_proto_depIdxs,
		EnumInfos:         file_ValueType_proto_enumTypes,
		MessageInfos:      file_ValueType_proto_msgTypes,
	}.Build()
	File_ValueType_proto = out.File
	file_ValueType_proto_rawDesc = nil
	file_ValueType_proto_goTypes = nil
	file_ValueType_proto_depIdxs = nil
}
