// Code generated by go-swagger; DO NOT EDIT.

package on_demand_feature_view_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	on_demand_feature_view_model "github.com/feast-dev/feast/backend/api/go_http_client/on_demand_feature_view_model"
)

// OnDemandFeatureViewServiceGetOnDemandFeatureViewReader is a Reader for the OnDemandFeatureViewServiceGetOnDemandFeatureView structure.
type OnDemandFeatureViewServiceGetOnDemandFeatureViewReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OnDemandFeatureViewServiceGetOnDemandFeatureViewReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOnDemandFeatureViewServiceGetOnDemandFeatureViewOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewOnDemandFeatureViewServiceGetOnDemandFeatureViewDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewOnDemandFeatureViewServiceGetOnDemandFeatureViewOK creates a OnDemandFeatureViewServiceGetOnDemandFeatureViewOK with default headers values
func NewOnDemandFeatureViewServiceGetOnDemandFeatureViewOK() *OnDemandFeatureViewServiceGetOnDemandFeatureViewOK {
	return &OnDemandFeatureViewServiceGetOnDemandFeatureViewOK{}
}

/*OnDemandFeatureViewServiceGetOnDemandFeatureViewOK handles this case with default header values.

A successful response.
*/
type OnDemandFeatureViewServiceGetOnDemandFeatureViewOK struct {
	Payload *on_demand_feature_view_model.APIOnDemandFeatureView
}

func (o *OnDemandFeatureViewServiceGetOnDemandFeatureViewOK) Error() string {
	return fmt.Sprintf("[GET /GetOnDemandFeatureView][%d] onDemandFeatureViewServiceGetOnDemandFeatureViewOK  %+v", 200, o.Payload)
}

func (o *OnDemandFeatureViewServiceGetOnDemandFeatureViewOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(on_demand_feature_view_model.APIOnDemandFeatureView)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOnDemandFeatureViewServiceGetOnDemandFeatureViewDefault creates a OnDemandFeatureViewServiceGetOnDemandFeatureViewDefault with default headers values
func NewOnDemandFeatureViewServiceGetOnDemandFeatureViewDefault(code int) *OnDemandFeatureViewServiceGetOnDemandFeatureViewDefault {
	return &OnDemandFeatureViewServiceGetOnDemandFeatureViewDefault{
		_statusCode: code,
	}
}

/*OnDemandFeatureViewServiceGetOnDemandFeatureViewDefault handles this case with default header values.

An unexpected error response.
*/
type OnDemandFeatureViewServiceGetOnDemandFeatureViewDefault struct {
	_statusCode int

	Payload *on_demand_feature_view_model.GatewayruntimeError
}

// Code gets the status code for the on demand feature view service get on demand feature view default response
func (o *OnDemandFeatureViewServiceGetOnDemandFeatureViewDefault) Code() int {
	return o._statusCode
}

func (o *OnDemandFeatureViewServiceGetOnDemandFeatureViewDefault) Error() string {
	return fmt.Sprintf("[GET /GetOnDemandFeatureView][%d] OnDemandFeatureViewService_GetOnDemandFeatureView default  %+v", o._statusCode, o.Payload)
}

func (o *OnDemandFeatureViewServiceGetOnDemandFeatureViewDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(on_demand_feature_view_model.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
