// Code generated by go-swagger; DO NOT EDIT.

package on_demand_feature_view_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	on_demand_feature_view_model "github.com/feast-dev/feast/backend/api/go_http_client/on_demand_feature_view_model"
)

// NewOnDemandFeatureViewServiceCreateOnDemandFeatureViewParams creates a new OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams object
// with the default values initialized.
func NewOnDemandFeatureViewServiceCreateOnDemandFeatureViewParams() *OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams {
	var ()
	return &OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOnDemandFeatureViewServiceCreateOnDemandFeatureViewParamsWithTimeout creates a new OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOnDemandFeatureViewServiceCreateOnDemandFeatureViewParamsWithTimeout(timeout time.Duration) *OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams {
	var ()
	return &OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams{

		timeout: timeout,
	}
}

// NewOnDemandFeatureViewServiceCreateOnDemandFeatureViewParamsWithContext creates a new OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams object
// with the default values initialized, and the ability to set a context for a request
func NewOnDemandFeatureViewServiceCreateOnDemandFeatureViewParamsWithContext(ctx context.Context) *OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams {
	var ()
	return &OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams{

		Context: ctx,
	}
}

// NewOnDemandFeatureViewServiceCreateOnDemandFeatureViewParamsWithHTTPClient creates a new OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOnDemandFeatureViewServiceCreateOnDemandFeatureViewParamsWithHTTPClient(client *http.Client) *OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams {
	var ()
	return &OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams{
		HTTPClient: client,
	}
}

/*OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams contains all the parameters to send to the API endpoint
for the on demand feature view service create on demand feature view operation typically these are written to a http.Request
*/
type OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams struct {

	/*Body*/
	Body *on_demand_feature_view_model.APIOnDemandFeatureView

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the on demand feature view service create on demand feature view params
func (o *OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams) WithTimeout(timeout time.Duration) *OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the on demand feature view service create on demand feature view params
func (o *OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the on demand feature view service create on demand feature view params
func (o *OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams) WithContext(ctx context.Context) *OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the on demand feature view service create on demand feature view params
func (o *OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the on demand feature view service create on demand feature view params
func (o *OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams) WithHTTPClient(client *http.Client) *OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the on demand feature view service create on demand feature view params
func (o *OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the on demand feature view service create on demand feature view params
func (o *OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams) WithBody(body *on_demand_feature_view_model.APIOnDemandFeatureView) *OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the on demand feature view service create on demand feature view params
func (o *OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams) SetBody(body *on_demand_feature_view_model.APIOnDemandFeatureView) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *OnDemandFeatureViewServiceCreateOnDemandFeatureViewParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
