// Code generated by go-swagger; DO NOT EDIT.

package on_demand_feature_view_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOnDemandFeatureViewServiceGetOnDemandFeatureViewParams creates a new OnDemandFeatureViewServiceGetOnDemandFeatureViewParams object
// with the default values initialized.
func NewOnDemandFeatureViewServiceGetOnDemandFeatureViewParams() *OnDemandFeatureViewServiceGetOnDemandFeatureViewParams {
	var ()
	return &OnDemandFeatureViewServiceGetOnDemandFeatureViewParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOnDemandFeatureViewServiceGetOnDemandFeatureViewParamsWithTimeout creates a new OnDemandFeatureViewServiceGetOnDemandFeatureViewParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOnDemandFeatureViewServiceGetOnDemandFeatureViewParamsWithTimeout(timeout time.Duration) *OnDemandFeatureViewServiceGetOnDemandFeatureViewParams {
	var ()
	return &OnDemandFeatureViewServiceGetOnDemandFeatureViewParams{

		timeout: timeout,
	}
}

// NewOnDemandFeatureViewServiceGetOnDemandFeatureViewParamsWithContext creates a new OnDemandFeatureViewServiceGetOnDemandFeatureViewParams object
// with the default values initialized, and the ability to set a context for a request
func NewOnDemandFeatureViewServiceGetOnDemandFeatureViewParamsWithContext(ctx context.Context) *OnDemandFeatureViewServiceGetOnDemandFeatureViewParams {
	var ()
	return &OnDemandFeatureViewServiceGetOnDemandFeatureViewParams{

		Context: ctx,
	}
}

// NewOnDemandFeatureViewServiceGetOnDemandFeatureViewParamsWithHTTPClient creates a new OnDemandFeatureViewServiceGetOnDemandFeatureViewParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOnDemandFeatureViewServiceGetOnDemandFeatureViewParamsWithHTTPClient(client *http.Client) *OnDemandFeatureViewServiceGetOnDemandFeatureViewParams {
	var ()
	return &OnDemandFeatureViewServiceGetOnDemandFeatureViewParams{
		HTTPClient: client,
	}
}

/*OnDemandFeatureViewServiceGetOnDemandFeatureViewParams contains all the parameters to send to the API endpoint
for the on demand feature view service get on demand feature view operation typically these are written to a http.Request
*/
type OnDemandFeatureViewServiceGetOnDemandFeatureViewParams struct {

	/*Name*/
	Name *string
	/*Project*/
	Project *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the on demand feature view service get on demand feature view params
func (o *OnDemandFeatureViewServiceGetOnDemandFeatureViewParams) WithTimeout(timeout time.Duration) *OnDemandFeatureViewServiceGetOnDemandFeatureViewParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the on demand feature view service get on demand feature view params
func (o *OnDemandFeatureViewServiceGetOnDemandFeatureViewParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the on demand feature view service get on demand feature view params
func (o *OnDemandFeatureViewServiceGetOnDemandFeatureViewParams) WithContext(ctx context.Context) *OnDemandFeatureViewServiceGetOnDemandFeatureViewParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the on demand feature view service get on demand feature view params
func (o *OnDemandFeatureViewServiceGetOnDemandFeatureViewParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the on demand feature view service get on demand feature view params
func (o *OnDemandFeatureViewServiceGetOnDemandFeatureViewParams) WithHTTPClient(client *http.Client) *OnDemandFeatureViewServiceGetOnDemandFeatureViewParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the on demand feature view service get on demand feature view params
func (o *OnDemandFeatureViewServiceGetOnDemandFeatureViewParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the on demand feature view service get on demand feature view params
func (o *OnDemandFeatureViewServiceGetOnDemandFeatureViewParams) WithName(name *string) *OnDemandFeatureViewServiceGetOnDemandFeatureViewParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the on demand feature view service get on demand feature view params
func (o *OnDemandFeatureViewServiceGetOnDemandFeatureViewParams) SetName(name *string) {
	o.Name = name
}

// WithProject adds the project to the on demand feature view service get on demand feature view params
func (o *OnDemandFeatureViewServiceGetOnDemandFeatureViewParams) WithProject(project *string) *OnDemandFeatureViewServiceGetOnDemandFeatureViewParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the on demand feature view service get on demand feature view params
func (o *OnDemandFeatureViewServiceGetOnDemandFeatureViewParams) SetProject(project *string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *OnDemandFeatureViewServiceGetOnDemandFeatureViewParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Project != nil {

		// query param project
		var qrProject string
		if o.Project != nil {
			qrProject = *o.Project
		}
		qProject := qrProject
		if qProject != "" {
			if err := r.SetQueryParam("project", qProject); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
