// Code generated by go-swagger; DO NOT EDIT.

package on_demand_feature_view_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	on_demand_feature_view_model "github.com/feast-dev/feast/backend/api/go_http_client/on_demand_feature_view_model"
)

// NewOnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams creates a new OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams object
// with the default values initialized.
func NewOnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams() *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams {
	var ()
	return &OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOnDemandFeatureViewServiceUpdateOnDemandFeatureViewParamsWithTimeout creates a new OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOnDemandFeatureViewServiceUpdateOnDemandFeatureViewParamsWithTimeout(timeout time.Duration) *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams {
	var ()
	return &OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams{

		timeout: timeout,
	}
}

// NewOnDemandFeatureViewServiceUpdateOnDemandFeatureViewParamsWithContext creates a new OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams object
// with the default values initialized, and the ability to set a context for a request
func NewOnDemandFeatureViewServiceUpdateOnDemandFeatureViewParamsWithContext(ctx context.Context) *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams {
	var ()
	return &OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams{

		Context: ctx,
	}
}

// NewOnDemandFeatureViewServiceUpdateOnDemandFeatureViewParamsWithHTTPClient creates a new OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOnDemandFeatureViewServiceUpdateOnDemandFeatureViewParamsWithHTTPClient(client *http.Client) *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams {
	var ()
	return &OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams{
		HTTPClient: client,
	}
}

/*OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams contains all the parameters to send to the API endpoint
for the on demand feature view service update on demand feature view operation typically these are written to a http.Request
*/
type OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams struct {

	/*Body*/
	Body *on_demand_feature_view_model.APIOnDemandFeatureView

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the on demand feature view service update on demand feature view params
func (o *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams) WithTimeout(timeout time.Duration) *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the on demand feature view service update on demand feature view params
func (o *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the on demand feature view service update on demand feature view params
func (o *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams) WithContext(ctx context.Context) *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the on demand feature view service update on demand feature view params
func (o *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the on demand feature view service update on demand feature view params
func (o *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams) WithHTTPClient(client *http.Client) *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the on demand feature view service update on demand feature view params
func (o *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the on demand feature view service update on demand feature view params
func (o *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams) WithBody(body *on_demand_feature_view_model.APIOnDemandFeatureView) *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the on demand feature view service update on demand feature view params
func (o *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams) SetBody(body *on_demand_feature_view_model.APIOnDemandFeatureView) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
