// Code generated by go-swagger; DO NOT EDIT.

package on_demand_feature_view_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	on_demand_feature_view_model "github.com/feast-dev/feast/backend/api/go_http_client/on_demand_feature_view_model"
)

// OnDemandFeatureViewServiceUpdateOnDemandFeatureViewReader is a Reader for the OnDemandFeatureViewServiceUpdateOnDemandFeatureView structure.
type OnDemandFeatureViewServiceUpdateOnDemandFeatureViewReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOnDemandFeatureViewServiceUpdateOnDemandFeatureViewOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewOnDemandFeatureViewServiceUpdateOnDemandFeatureViewDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewOnDemandFeatureViewServiceUpdateOnDemandFeatureViewOK creates a OnDemandFeatureViewServiceUpdateOnDemandFeatureViewOK with default headers values
func NewOnDemandFeatureViewServiceUpdateOnDemandFeatureViewOK() *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewOK {
	return &OnDemandFeatureViewServiceUpdateOnDemandFeatureViewOK{}
}

/*OnDemandFeatureViewServiceUpdateOnDemandFeatureViewOK handles this case with default header values.

A successful response.
*/
type OnDemandFeatureViewServiceUpdateOnDemandFeatureViewOK struct {
	Payload *on_demand_feature_view_model.APIOnDemandFeatureView
}

func (o *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewOK) Error() string {
	return fmt.Sprintf("[POST /UpdateOnDemandFeatureView][%d] onDemandFeatureViewServiceUpdateOnDemandFeatureViewOK  %+v", 200, o.Payload)
}

func (o *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(on_demand_feature_view_model.APIOnDemandFeatureView)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOnDemandFeatureViewServiceUpdateOnDemandFeatureViewDefault creates a OnDemandFeatureViewServiceUpdateOnDemandFeatureViewDefault with default headers values
func NewOnDemandFeatureViewServiceUpdateOnDemandFeatureViewDefault(code int) *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewDefault {
	return &OnDemandFeatureViewServiceUpdateOnDemandFeatureViewDefault{
		_statusCode: code,
	}
}

/*OnDemandFeatureViewServiceUpdateOnDemandFeatureViewDefault handles this case with default header values.

An unexpected error response.
*/
type OnDemandFeatureViewServiceUpdateOnDemandFeatureViewDefault struct {
	_statusCode int

	Payload *on_demand_feature_view_model.GatewayruntimeError
}

// Code gets the status code for the on demand feature view service update on demand feature view default response
func (o *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewDefault) Code() int {
	return o._statusCode
}

func (o *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewDefault) Error() string {
	return fmt.Sprintf("[POST /UpdateOnDemandFeatureView][%d] OnDemandFeatureViewService_UpdateOnDemandFeatureView default  %+v", o._statusCode, o.Payload)
}

func (o *OnDemandFeatureViewServiceUpdateOnDemandFeatureViewDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(on_demand_feature_view_model.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
