// Code generated by go-swagger; DO NOT EDIT.

package on_demand_feature_view_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	on_demand_feature_view_model "github.com/feast-dev/feast/backend/api/go_http_client/on_demand_feature_view_model"
)

// OnDemandFeatureViewServiceCreateOnDemandFeatureViewReader is a Reader for the OnDemandFeatureViewServiceCreateOnDemandFeatureView structure.
type OnDemandFeatureViewServiceCreateOnDemandFeatureViewReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OnDemandFeatureViewServiceCreateOnDemandFeatureViewReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOnDemandFeatureViewServiceCreateOnDemandFeatureViewOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewOnDemandFeatureViewServiceCreateOnDemandFeatureViewDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewOnDemandFeatureViewServiceCreateOnDemandFeatureViewOK creates a OnDemandFeatureViewServiceCreateOnDemandFeatureViewOK with default headers values
func NewOnDemandFeatureViewServiceCreateOnDemandFeatureViewOK() *OnDemandFeatureViewServiceCreateOnDemandFeatureViewOK {
	return &OnDemandFeatureViewServiceCreateOnDemandFeatureViewOK{}
}

/*OnDemandFeatureViewServiceCreateOnDemandFeatureViewOK handles this case with default header values.

A successful response.
*/
type OnDemandFeatureViewServiceCreateOnDemandFeatureViewOK struct {
	Payload *on_demand_feature_view_model.APIOnDemandFeatureView
}

func (o *OnDemandFeatureViewServiceCreateOnDemandFeatureViewOK) Error() string {
	return fmt.Sprintf("[POST /CreateOnDemandFeatureView][%d] onDemandFeatureViewServiceCreateOnDemandFeatureViewOK  %+v", 200, o.Payload)
}

func (o *OnDemandFeatureViewServiceCreateOnDemandFeatureViewOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(on_demand_feature_view_model.APIOnDemandFeatureView)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOnDemandFeatureViewServiceCreateOnDemandFeatureViewDefault creates a OnDemandFeatureViewServiceCreateOnDemandFeatureViewDefault with default headers values
func NewOnDemandFeatureViewServiceCreateOnDemandFeatureViewDefault(code int) *OnDemandFeatureViewServiceCreateOnDemandFeatureViewDefault {
	return &OnDemandFeatureViewServiceCreateOnDemandFeatureViewDefault{
		_statusCode: code,
	}
}

/*OnDemandFeatureViewServiceCreateOnDemandFeatureViewDefault handles this case with default header values.

An unexpected error response.
*/
type OnDemandFeatureViewServiceCreateOnDemandFeatureViewDefault struct {
	_statusCode int

	Payload *on_demand_feature_view_model.GatewayruntimeError
}

// Code gets the status code for the on demand feature view service create on demand feature view default response
func (o *OnDemandFeatureViewServiceCreateOnDemandFeatureViewDefault) Code() int {
	return o._statusCode
}

func (o *OnDemandFeatureViewServiceCreateOnDemandFeatureViewDefault) Error() string {
	return fmt.Sprintf("[POST /CreateOnDemandFeatureView][%d] OnDemandFeatureViewService_CreateOnDemandFeatureView default  %+v", o._statusCode, o.Payload)
}

func (o *OnDemandFeatureViewServiceCreateOnDemandFeatureViewDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(on_demand_feature_view_model.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
