// Code generated by go-swagger; DO NOT EDIT.

package on_demand_feature_view_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	on_demand_feature_view_model "github.com/feast-dev/feast/backend/api/go_http_client/on_demand_feature_view_model"
)

// OnDemandFeatureViewServiceDeleteOnDemandFeatureViewReader is a Reader for the OnDemandFeatureViewServiceDeleteOnDemandFeatureView structure.
type OnDemandFeatureViewServiceDeleteOnDemandFeatureViewReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OnDemandFeatureViewServiceDeleteOnDemandFeatureViewReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewOnDemandFeatureViewServiceDeleteOnDemandFeatureViewOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewOnDemandFeatureViewServiceDeleteOnDemandFeatureViewDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewOnDemandFeatureViewServiceDeleteOnDemandFeatureViewOK creates a OnDemandFeatureViewServiceDeleteOnDemandFeatureViewOK with default headers values
func NewOnDemandFeatureViewServiceDeleteOnDemandFeatureViewOK() *OnDemandFeatureViewServiceDeleteOnDemandFeatureViewOK {
	return &OnDemandFeatureViewServiceDeleteOnDemandFeatureViewOK{}
}

/*OnDemandFeatureViewServiceDeleteOnDemandFeatureViewOK handles this case with default header values.

A successful response.
*/
type OnDemandFeatureViewServiceDeleteOnDemandFeatureViewOK struct {
	Payload interface{}
}

func (o *OnDemandFeatureViewServiceDeleteOnDemandFeatureViewOK) Error() string {
	return fmt.Sprintf("[DELETE /DeleteOnDemandFeatureView][%d] onDemandFeatureViewServiceDeleteOnDemandFeatureViewOK  %+v", 200, o.Payload)
}

func (o *OnDemandFeatureViewServiceDeleteOnDemandFeatureViewOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOnDemandFeatureViewServiceDeleteOnDemandFeatureViewDefault creates a OnDemandFeatureViewServiceDeleteOnDemandFeatureViewDefault with default headers values
func NewOnDemandFeatureViewServiceDeleteOnDemandFeatureViewDefault(code int) *OnDemandFeatureViewServiceDeleteOnDemandFeatureViewDefault {
	return &OnDemandFeatureViewServiceDeleteOnDemandFeatureViewDefault{
		_statusCode: code,
	}
}

/*OnDemandFeatureViewServiceDeleteOnDemandFeatureViewDefault handles this case with default header values.

An unexpected error response.
*/
type OnDemandFeatureViewServiceDeleteOnDemandFeatureViewDefault struct {
	_statusCode int

	Payload *on_demand_feature_view_model.GatewayruntimeError
}

// Code gets the status code for the on demand feature view service delete on demand feature view default response
func (o *OnDemandFeatureViewServiceDeleteOnDemandFeatureViewDefault) Code() int {
	return o._statusCode
}

func (o *OnDemandFeatureViewServiceDeleteOnDemandFeatureViewDefault) Error() string {
	return fmt.Sprintf("[DELETE /DeleteOnDemandFeatureView][%d] OnDemandFeatureViewService_DeleteOnDemandFeatureView default  %+v", o._statusCode, o.Payload)
}

func (o *OnDemandFeatureViewServiceDeleteOnDemandFeatureViewDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(on_demand_feature_view_model.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
