// Code generated by go-swagger; DO NOT EDIT.

package feature_view_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	feature_view_model "github.com/feast-dev/feast/backend/api/go_http_client/feature_view_model"
)

// FeatureViewServiceCreateFeatureViewReader is a Reader for the FeatureViewServiceCreateFeatureView structure.
type FeatureViewServiceCreateFeatureViewReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FeatureViewServiceCreateFeatureViewReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewFeatureViewServiceCreateFeatureViewOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewFeatureViewServiceCreateFeatureViewDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewFeatureViewServiceCreateFeatureViewOK creates a FeatureViewServiceCreateFeatureViewOK with default headers values
func NewFeatureViewServiceCreateFeatureViewOK() *FeatureViewServiceCreateFeatureViewOK {
	return &FeatureViewServiceCreateFeatureViewOK{}
}

/*FeatureViewServiceCreateFeatureViewOK handles this case with default header values.

A successful response.
*/
type FeatureViewServiceCreateFeatureViewOK struct {
	Payload *feature_view_model.APIFeatureView
}

func (o *FeatureViewServiceCreateFeatureViewOK) Error() string {
	return fmt.Sprintf("[POST /CreateFeatureView][%d] featureViewServiceCreateFeatureViewOK  %+v", 200, o.Payload)
}

func (o *FeatureViewServiceCreateFeatureViewOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(feature_view_model.APIFeatureView)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFeatureViewServiceCreateFeatureViewDefault creates a FeatureViewServiceCreateFeatureViewDefault with default headers values
func NewFeatureViewServiceCreateFeatureViewDefault(code int) *FeatureViewServiceCreateFeatureViewDefault {
	return &FeatureViewServiceCreateFeatureViewDefault{
		_statusCode: code,
	}
}

/*FeatureViewServiceCreateFeatureViewDefault handles this case with default header values.

An unexpected error response.
*/
type FeatureViewServiceCreateFeatureViewDefault struct {
	_statusCode int

	Payload *feature_view_model.GatewayruntimeError
}

// Code gets the status code for the feature view service create feature view default response
func (o *FeatureViewServiceCreateFeatureViewDefault) Code() int {
	return o._statusCode
}

func (o *FeatureViewServiceCreateFeatureViewDefault) Error() string {
	return fmt.Sprintf("[POST /CreateFeatureView][%d] FeatureViewService_CreateFeatureView default  %+v", o._statusCode, o.Payload)
}

func (o *FeatureViewServiceCreateFeatureViewDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(feature_view_model.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
