// Code generated by go-swagger; DO NOT EDIT.

package feature_view_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	feature_view_model "github.com/feast-dev/feast/backend/api/go_http_client/feature_view_model"
)

// NewFeatureViewServiceReportMIParams creates a new FeatureViewServiceReportMIParams object
// with the default values initialized.
func NewFeatureViewServiceReportMIParams() *FeatureViewServiceReportMIParams {
	var ()
	return &FeatureViewServiceReportMIParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFeatureViewServiceReportMIParamsWithTimeout creates a new FeatureViewServiceReportMIParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFeatureViewServiceReportMIParamsWithTimeout(timeout time.Duration) *FeatureViewServiceReportMIParams {
	var ()
	return &FeatureViewServiceReportMIParams{

		timeout: timeout,
	}
}

// NewFeatureViewServiceReportMIParamsWithContext creates a new FeatureViewServiceReportMIParams object
// with the default values initialized, and the ability to set a context for a request
func NewFeatureViewServiceReportMIParamsWithContext(ctx context.Context) *FeatureViewServiceReportMIParams {
	var ()
	return &FeatureViewServiceReportMIParams{

		Context: ctx,
	}
}

// NewFeatureViewServiceReportMIParamsWithHTTPClient creates a new FeatureViewServiceReportMIParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFeatureViewServiceReportMIParamsWithHTTPClient(client *http.Client) *FeatureViewServiceReportMIParams {
	var ()
	return &FeatureViewServiceReportMIParams{
		HTTPClient: client,
	}
}

/*FeatureViewServiceReportMIParams contains all the parameters to send to the API endpoint
for the feature view service report m i operation typically these are written to a http.Request
*/
type FeatureViewServiceReportMIParams struct {

	/*Body*/
	Body *feature_view_model.APIMaterializationInterval
	/*Name*/
	Name *string
	/*Project*/
	Project *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the feature view service report m i params
func (o *FeatureViewServiceReportMIParams) WithTimeout(timeout time.Duration) *FeatureViewServiceReportMIParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the feature view service report m i params
func (o *FeatureViewServiceReportMIParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the feature view service report m i params
func (o *FeatureViewServiceReportMIParams) WithContext(ctx context.Context) *FeatureViewServiceReportMIParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the feature view service report m i params
func (o *FeatureViewServiceReportMIParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the feature view service report m i params
func (o *FeatureViewServiceReportMIParams) WithHTTPClient(client *http.Client) *FeatureViewServiceReportMIParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the feature view service report m i params
func (o *FeatureViewServiceReportMIParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the feature view service report m i params
func (o *FeatureViewServiceReportMIParams) WithBody(body *feature_view_model.APIMaterializationInterval) *FeatureViewServiceReportMIParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the feature view service report m i params
func (o *FeatureViewServiceReportMIParams) SetBody(body *feature_view_model.APIMaterializationInterval) {
	o.Body = body
}

// WithName adds the name to the feature view service report m i params
func (o *FeatureViewServiceReportMIParams) WithName(name *string) *FeatureViewServiceReportMIParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the feature view service report m i params
func (o *FeatureViewServiceReportMIParams) SetName(name *string) {
	o.Name = name
}

// WithProject adds the project to the feature view service report m i params
func (o *FeatureViewServiceReportMIParams) WithProject(project *string) *FeatureViewServiceReportMIParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the feature view service report m i params
func (o *FeatureViewServiceReportMIParams) SetProject(project *string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *FeatureViewServiceReportMIParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Project != nil {

		// query param project
		var qrProject string
		if o.Project != nil {
			qrProject = *o.Project
		}
		qProject := qrProject
		if qProject != "" {
			if err := r.SetQueryParam("project", qProject); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
