// Code generated by go-swagger; DO NOT EDIT.

package feature_view_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	feature_view_model "github.com/feast-dev/feast/backend/api/go_http_client/feature_view_model"
)

// NewFeatureViewServiceCreateFeatureViewParams creates a new FeatureViewServiceCreateFeatureViewParams object
// with the default values initialized.
func NewFeatureViewServiceCreateFeatureViewParams() *FeatureViewServiceCreateFeatureViewParams {
	var ()
	return &FeatureViewServiceCreateFeatureViewParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFeatureViewServiceCreateFeatureViewParamsWithTimeout creates a new FeatureViewServiceCreateFeatureViewParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFeatureViewServiceCreateFeatureViewParamsWithTimeout(timeout time.Duration) *FeatureViewServiceCreateFeatureViewParams {
	var ()
	return &FeatureViewServiceCreateFeatureViewParams{

		timeout: timeout,
	}
}

// NewFeatureViewServiceCreateFeatureViewParamsWithContext creates a new FeatureViewServiceCreateFeatureViewParams object
// with the default values initialized, and the ability to set a context for a request
func NewFeatureViewServiceCreateFeatureViewParamsWithContext(ctx context.Context) *FeatureViewServiceCreateFeatureViewParams {
	var ()
	return &FeatureViewServiceCreateFeatureViewParams{

		Context: ctx,
	}
}

// NewFeatureViewServiceCreateFeatureViewParamsWithHTTPClient creates a new FeatureViewServiceCreateFeatureViewParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFeatureViewServiceCreateFeatureViewParamsWithHTTPClient(client *http.Client) *FeatureViewServiceCreateFeatureViewParams {
	var ()
	return &FeatureViewServiceCreateFeatureViewParams{
		HTTPClient: client,
	}
}

/*FeatureViewServiceCreateFeatureViewParams contains all the parameters to send to the API endpoint
for the feature view service create feature view operation typically these are written to a http.Request
*/
type FeatureViewServiceCreateFeatureViewParams struct {

	/*Body*/
	Body *feature_view_model.APIFeatureView

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the feature view service create feature view params
func (o *FeatureViewServiceCreateFeatureViewParams) WithTimeout(timeout time.Duration) *FeatureViewServiceCreateFeatureViewParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the feature view service create feature view params
func (o *FeatureViewServiceCreateFeatureViewParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the feature view service create feature view params
func (o *FeatureViewServiceCreateFeatureViewParams) WithContext(ctx context.Context) *FeatureViewServiceCreateFeatureViewParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the feature view service create feature view params
func (o *FeatureViewServiceCreateFeatureViewParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the feature view service create feature view params
func (o *FeatureViewServiceCreateFeatureViewParams) WithHTTPClient(client *http.Client) *FeatureViewServiceCreateFeatureViewParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the feature view service create feature view params
func (o *FeatureViewServiceCreateFeatureViewParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the feature view service create feature view params
func (o *FeatureViewServiceCreateFeatureViewParams) WithBody(body *feature_view_model.APIFeatureView) *FeatureViewServiceCreateFeatureViewParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the feature view service create feature view params
func (o *FeatureViewServiceCreateFeatureViewParams) SetBody(body *feature_view_model.APIFeatureView) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *FeatureViewServiceCreateFeatureViewParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
