// Code generated by go-swagger; DO NOT EDIT.

package feature_view_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	feature_view_model "github.com/feast-dev/feast/backend/api/go_http_client/feature_view_model"
)

// FeatureViewServiceDeleteFeatureViewReader is a Reader for the FeatureViewServiceDeleteFeatureView structure.
type FeatureViewServiceDeleteFeatureViewReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FeatureViewServiceDeleteFeatureViewReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewFeatureViewServiceDeleteFeatureViewOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewFeatureViewServiceDeleteFeatureViewDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewFeatureViewServiceDeleteFeatureViewOK creates a FeatureViewServiceDeleteFeatureViewOK with default headers values
func NewFeatureViewServiceDeleteFeatureViewOK() *FeatureViewServiceDeleteFeatureViewOK {
	return &FeatureViewServiceDeleteFeatureViewOK{}
}

/*FeatureViewServiceDeleteFeatureViewOK handles this case with default header values.

A successful response.
*/
type FeatureViewServiceDeleteFeatureViewOK struct {
	Payload interface{}
}

func (o *FeatureViewServiceDeleteFeatureViewOK) Error() string {
	return fmt.Sprintf("[DELETE /DeleteFeatureView][%d] featureViewServiceDeleteFeatureViewOK  %+v", 200, o.Payload)
}

func (o *FeatureViewServiceDeleteFeatureViewOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFeatureViewServiceDeleteFeatureViewDefault creates a FeatureViewServiceDeleteFeatureViewDefault with default headers values
func NewFeatureViewServiceDeleteFeatureViewDefault(code int) *FeatureViewServiceDeleteFeatureViewDefault {
	return &FeatureViewServiceDeleteFeatureViewDefault{
		_statusCode: code,
	}
}

/*FeatureViewServiceDeleteFeatureViewDefault handles this case with default header values.

An unexpected error response.
*/
type FeatureViewServiceDeleteFeatureViewDefault struct {
	_statusCode int

	Payload *feature_view_model.GatewayruntimeError
}

// Code gets the status code for the feature view service delete feature view default response
func (o *FeatureViewServiceDeleteFeatureViewDefault) Code() int {
	return o._statusCode
}

func (o *FeatureViewServiceDeleteFeatureViewDefault) Error() string {
	return fmt.Sprintf("[DELETE /DeleteFeatureView][%d] FeatureViewService_DeleteFeatureView default  %+v", o._statusCode, o.Payload)
}

func (o *FeatureViewServiceDeleteFeatureViewDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(feature_view_model.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
