# coding: utf-8

"""
    Feast Registry API

    This file contains REST API specification for Feast Registry. The file is autogenerated from the swagger definition.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from frs_api.configuration import Configuration


class ApiListFeatureServicesResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'feature_services': 'list[ApiFeatureService]'
    }

    attribute_map = {
        'feature_services': 'feature_services'
    }

    def __init__(self, feature_services=None, local_vars_configuration=None):  # noqa: E501
        """ApiListFeatureServicesResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._feature_services = None
        self.discriminator = None

        if feature_services is not None:
            self.feature_services = feature_services

    @property
    def feature_services(self):
        """Gets the feature_services of this ApiListFeatureServicesResponse.  # noqa: E501


        :return: The feature_services of this ApiListFeatureServicesResponse.  # noqa: E501
        :rtype: list[ApiFeatureService]
        """
        return self._feature_services

    @feature_services.setter
    def feature_services(self, feature_services):
        """Sets the feature_services of this ApiListFeatureServicesResponse.


        :param feature_services: The feature_services of this ApiListFeatureServicesResponse.  # noqa: E501
        :type: list[ApiFeatureService]
        """

        self._feature_services = feature_services

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiListFeatureServicesResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ApiListFeatureServicesResponse):
            return True

        return self.to_dict() != other.to_dict()
