# coding: utf-8

"""
    Feast Registry API

    This file contains REST API specification for Feast Registry. The file is autogenerated from the swagger definition.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from frs_api.configuration import Configuration


class ApiProject(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'registry_schema_version': 'str',
        'version_id': 'str',
        'last_updated': 'datetime'
    }

    attribute_map = {
        'name': 'name',
        'registry_schema_version': 'registry_schema_version',
        'version_id': 'version_id',
        'last_updated': 'last_updated'
    }

    def __init__(self, name=None, registry_schema_version=None, version_id=None, last_updated=None, local_vars_configuration=None):  # noqa: E501
        """ApiProject - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._registry_schema_version = None
        self._version_id = None
        self._last_updated = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if registry_schema_version is not None:
            self.registry_schema_version = registry_schema_version
        if version_id is not None:
            self.version_id = version_id
        if last_updated is not None:
            self.last_updated = last_updated

    @property
    def name(self):
        """Gets the name of this ApiProject.  # noqa: E501

        Name of Feast project.  # noqa: E501

        :return: The name of this ApiProject.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ApiProject.

        Name of Feast project.  # noqa: E501

        :param name: The name of this ApiProject.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def registry_schema_version(self):
        """Gets the registry_schema_version of this ApiProject.  # noqa: E501


        :return: The registry_schema_version of this ApiProject.  # noqa: E501
        :rtype: str
        """
        return self._registry_schema_version

    @registry_schema_version.setter
    def registry_schema_version(self, registry_schema_version):
        """Sets the registry_schema_version of this ApiProject.


        :param registry_schema_version: The registry_schema_version of this ApiProject.  # noqa: E501
        :type: str
        """

        self._registry_schema_version = registry_schema_version

    @property
    def version_id(self):
        """Gets the version_id of this ApiProject.  # noqa: E501


        :return: The version_id of this ApiProject.  # noqa: E501
        :rtype: str
        """
        return self._version_id

    @version_id.setter
    def version_id(self, version_id):
        """Sets the version_id of this ApiProject.


        :param version_id: The version_id of this ApiProject.  # noqa: E501
        :type: str
        """

        self._version_id = version_id

    @property
    def last_updated(self):
        """Gets the last_updated of this ApiProject.  # noqa: E501

        Last update time of the project.  # noqa: E501

        :return: The last_updated of this ApiProject.  # noqa: E501
        :rtype: datetime
        """
        return self._last_updated

    @last_updated.setter
    def last_updated(self, last_updated):
        """Sets the last_updated of this ApiProject.

        Last update time of the project.  # noqa: E501

        :param last_updated: The last_updated of this ApiProject.  # noqa: E501
        :type: datetime
        """

        self._last_updated = last_updated

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiProject):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ApiProject):
            return True

        return self.to_dict() != other.to_dict()
