# coding: utf-8

"""
    Feast Registry API

    This file contains REST API specification for Feast Registry. The file is autogenerated from the swagger definition.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from frs_api.configuration import Configuration


class ApiFeature(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'value_type': 'ValueTypeEnum',
        'tags': 'dict(str, str)'
    }

    attribute_map = {
        'name': 'name',
        'value_type': 'value_type',
        'tags': 'tags'
    }

    def __init__(self, name=None, value_type=None, tags=None, local_vars_configuration=None):  # noqa: E501
        """ApiFeature - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._value_type = None
        self._tags = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if value_type is not None:
            self.value_type = value_type
        if tags is not None:
            self.tags = tags

    @property
    def name(self):
        """Gets the name of this ApiFeature.  # noqa: E501

        Name of the feature. Not updatable.  # noqa: E501

        :return: The name of this ApiFeature.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ApiFeature.

        Name of the feature. Not updatable.  # noqa: E501

        :param name: The name of this ApiFeature.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def value_type(self):
        """Gets the value_type of this ApiFeature.  # noqa: E501


        :return: The value_type of this ApiFeature.  # noqa: E501
        :rtype: ValueTypeEnum
        """
        return self._value_type

    @value_type.setter
    def value_type(self, value_type):
        """Sets the value_type of this ApiFeature.


        :param value_type: The value_type of this ApiFeature.  # noqa: E501
        :type: ValueTypeEnum
        """

        self._value_type = value_type

    @property
    def tags(self):
        """Gets the tags of this ApiFeature.  # noqa: E501

        Tags for user defined metadata on a feature.  # noqa: E501

        :return: The tags of this ApiFeature.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this ApiFeature.

        Tags for user defined metadata on a feature.  # noqa: E501

        :param tags: The tags of this ApiFeature.  # noqa: E501
        :type: dict(str, str)
        """

        self._tags = tags

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiFeature):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ApiFeature):
            return True

        return self.to_dict() != other.to_dict()
