# coding: utf-8

"""
    Feast Registry API

    This file contains REST API specification for Feast Registry. The file is autogenerated from the swagger definition.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from frs_api.configuration import Configuration


class ApiInfraObject(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'infra_object_class_type': 'str',
        'infra_object': 'str'
    }

    attribute_map = {
        'infra_object_class_type': 'infra_object_class_type',
        'infra_object': 'infra_object'
    }

    def __init__(self, infra_object_class_type=None, infra_object=None, local_vars_configuration=None):  # noqa: E501
        """ApiInfraObject - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._infra_object_class_type = None
        self._infra_object = None
        self.discriminator = None

        if infra_object_class_type is not None:
            self.infra_object_class_type = infra_object_class_type
        if infra_object is not None:
            self.infra_object = infra_object

    @property
    def infra_object_class_type(self):
        """Gets the infra_object_class_type of this ApiInfraObject.  # noqa: E501

        Represents the Python class for the infrastructure object.  # noqa: E501

        :return: The infra_object_class_type of this ApiInfraObject.  # noqa: E501
        :rtype: str
        """
        return self._infra_object_class_type

    @infra_object_class_type.setter
    def infra_object_class_type(self, infra_object_class_type):
        """Sets the infra_object_class_type of this ApiInfraObject.

        Represents the Python class for the infrastructure object.  # noqa: E501

        :param infra_object_class_type: The infra_object_class_type of this ApiInfraObject.  # noqa: E501
        :type: str
        """

        self._infra_object_class_type = infra_object_class_type

    @property
    def infra_object(self):
        """Gets the infra_object of this ApiInfraObject.  # noqa: E501

        The infrastructure object. Protobuf object transformed to a JSON string.  # noqa: E501

        :return: The infra_object of this ApiInfraObject.  # noqa: E501
        :rtype: str
        """
        return self._infra_object

    @infra_object.setter
    def infra_object(self, infra_object):
        """Sets the infra_object of this ApiInfraObject.

        The infrastructure object. Protobuf object transformed to a JSON string.  # noqa: E501

        :param infra_object: The infra_object of this ApiInfraObject.  # noqa: E501
        :type: str
        """

        self._infra_object = infra_object

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiInfraObject):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ApiInfraObject):
            return True

        return self.to_dict() != other.to_dict()
