# coding: utf-8

"""
    Feast Registry API

    This file contains REST API specification for Feast Registry. The file is autogenerated from the swagger definition.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from frs_api.configuration import Configuration


class ApiFeatureService(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'project': 'str',
        'features': 'list[ApiFeatureViewProjection]',
        'tags': 'dict(str, str)',
        'description': 'str',
        'owner': 'str',
        'logging_config': 'str',
        'created_timestamp': 'datetime',
        'last_updated_timestamp': 'datetime'
    }

    attribute_map = {
        'name': 'name',
        'project': 'project',
        'features': 'features',
        'tags': 'tags',
        'description': 'description',
        'owner': 'owner',
        'logging_config': 'logging_config',
        'created_timestamp': 'created_timestamp',
        'last_updated_timestamp': 'last_updated_timestamp'
    }

    def __init__(self, name=None, project=None, features=None, tags=None, description=None, owner=None, logging_config=None, created_timestamp=None, last_updated_timestamp=None, local_vars_configuration=None):  # noqa: E501
        """ApiFeatureService - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._project = None
        self._features = None
        self._tags = None
        self._description = None
        self._owner = None
        self._logging_config = None
        self._created_timestamp = None
        self._last_updated_timestamp = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if project is not None:
            self.project = project
        if features is not None:
            self.features = features
        if tags is not None:
            self.tags = tags
        if description is not None:
            self.description = description
        if owner is not None:
            self.owner = owner
        if logging_config is not None:
            self.logging_config = logging_config
        if created_timestamp is not None:
            self.created_timestamp = created_timestamp
        if last_updated_timestamp is not None:
            self.last_updated_timestamp = last_updated_timestamp

    @property
    def name(self):
        """Gets the name of this ApiFeatureService.  # noqa: E501

        Name of the feature service. Must be unique. Not updated.  # noqa: E501

        :return: The name of this ApiFeatureService.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ApiFeatureService.

        Name of the feature service. Must be unique. Not updated.  # noqa: E501

        :param name: The name of this ApiFeatureService.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def project(self):
        """Gets the project of this ApiFeatureService.  # noqa: E501

        Name of Feast project that this feature service belongs to.  # noqa: E501

        :return: The project of this ApiFeatureService.  # noqa: E501
        :rtype: str
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this ApiFeatureService.

        Name of Feast project that this feature service belongs to.  # noqa: E501

        :param project: The project of this ApiFeatureService.  # noqa: E501
        :type: str
        """

        self._project = project

    @property
    def features(self):
        """Gets the features of this ApiFeatureService.  # noqa: E501

        Represents a projection that's to be applied on top of the FeatureView. Contains data such as the features to use from a FeatureView.  # noqa: E501

        :return: The features of this ApiFeatureService.  # noqa: E501
        :rtype: list[ApiFeatureViewProjection]
        """
        return self._features

    @features.setter
    def features(self, features):
        """Sets the features of this ApiFeatureService.

        Represents a projection that's to be applied on top of the FeatureView. Contains data such as the features to use from a FeatureView.  # noqa: E501

        :param features: The features of this ApiFeatureService.  # noqa: E501
        :type: list[ApiFeatureViewProjection]
        """

        self._features = features

    @property
    def tags(self):
        """Gets the tags of this ApiFeatureService.  # noqa: E501

        User defined metadata.  # noqa: E501

        :return: The tags of this ApiFeatureService.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this ApiFeatureService.

        User defined metadata.  # noqa: E501

        :param tags: The tags of this ApiFeatureService.  # noqa: E501
        :type: dict(str, str)
        """

        self._tags = tags

    @property
    def description(self):
        """Gets the description of this ApiFeatureService.  # noqa: E501

        Description of the feature service.  # noqa: E501

        :return: The description of this ApiFeatureService.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ApiFeatureService.

        Description of the feature service.  # noqa: E501

        :param description: The description of this ApiFeatureService.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def owner(self):
        """Gets the owner of this ApiFeatureService.  # noqa: E501

        Owner of the feature service.  # noqa: E501

        :return: The owner of this ApiFeatureService.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this ApiFeatureService.

        Owner of the feature service.  # noqa: E501

        :param owner: The owner of this ApiFeatureService.  # noqa: E501
        :type: str
        """

        self._owner = owner

    @property
    def logging_config(self):
        """Gets the logging_config of this ApiFeatureService.  # noqa: E501

        (optional) If provided logging will be enabled for this feature service. Protobuf object transformed to a JSON string.  # noqa: E501

        :return: The logging_config of this ApiFeatureService.  # noqa: E501
        :rtype: str
        """
        return self._logging_config

    @logging_config.setter
    def logging_config(self, logging_config):
        """Sets the logging_config of this ApiFeatureService.

        (optional) If provided logging will be enabled for this feature service. Protobuf object transformed to a JSON string.  # noqa: E501

        :param logging_config: The logging_config of this ApiFeatureService.  # noqa: E501
        :type: str
        """

        self._logging_config = logging_config

    @property
    def created_timestamp(self):
        """Gets the created_timestamp of this ApiFeatureService.  # noqa: E501

        Creation time of the feature service.  # noqa: E501

        :return: The created_timestamp of this ApiFeatureService.  # noqa: E501
        :rtype: datetime
        """
        return self._created_timestamp

    @created_timestamp.setter
    def created_timestamp(self, created_timestamp):
        """Sets the created_timestamp of this ApiFeatureService.

        Creation time of the feature service.  # noqa: E501

        :param created_timestamp: The created_timestamp of this ApiFeatureService.  # noqa: E501
        :type: datetime
        """

        self._created_timestamp = created_timestamp

    @property
    def last_updated_timestamp(self):
        """Gets the last_updated_timestamp of this ApiFeatureService.  # noqa: E501

        Last update time of the feature service.  # noqa: E501

        :return: The last_updated_timestamp of this ApiFeatureService.  # noqa: E501
        :rtype: datetime
        """
        return self._last_updated_timestamp

    @last_updated_timestamp.setter
    def last_updated_timestamp(self, last_updated_timestamp):
        """Sets the last_updated_timestamp of this ApiFeatureService.

        Last update time of the feature service.  # noqa: E501

        :param last_updated_timestamp: The last_updated_timestamp of this ApiFeatureService.  # noqa: E501
        :type: datetime
        """

        self._last_updated_timestamp = last_updated_timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiFeatureService):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ApiFeatureService):
            return True

        return self.to_dict() != other.to_dict()
