# coding: utf-8

"""
    Feast Registry API

    This file contains REST API specification for Feast Registry. The file is autogenerated from the swagger definition.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from frs_api.configuration import Configuration


class DataSourceSourceType(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    INVALID = "INVALID"
    BATCH_FILE = "BATCH_FILE"
    BATCH_SNOWFLAKE = "BATCH_SNOWFLAKE"
    BATCH_BIGQUERY = "BATCH_BIGQUERY"
    BATCH_REDSHIFT = "BATCH_REDSHIFT"
    STREAM_KAFKA = "STREAM_KAFKA"
    STREAM_KINESIS = "STREAM_KINESIS"
    CUSTOM_SOURCE = "CUSTOM_SOURCE"
    REQUEST_SOURCE = "REQUEST_SOURCE"
    PUSH_SOURCE = "PUSH_SOURCE"
    BATCH_TRINO = "BATCH_TRINO"
    BATCH_SPARK = "BATCH_SPARK"

    allowable_values = [INVALID, BATCH_FILE, BATCH_SNOWFLAKE, BATCH_BIGQUERY, BATCH_REDSHIFT, STREAM_KAFKA, STREAM_KINESIS, CUSTOM_SOURCE, REQUEST_SOURCE, PUSH_SOURCE, BATCH_TRINO, BATCH_SPARK]  # noqa: E501

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
    }

    attribute_map = {
    }

    def __init__(self, local_vars_configuration=None):  # noqa: E501
        """DataSourceSourceType - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataSourceSourceType):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DataSourceSourceType):
            return True

        return self.to_dict() != other.to_dict()
