apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-d
  namespace: default
  labels:
    app: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        image: confluentinc/cp-zookeeper:6.2.0
        ports:
        - name: zookeeper-cli
          containerPort: 2181
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: default
spec:
  type: ClusterIP
  ports:
  - name: zookeeper
    port: 2181
    targetPort: zookeeper-cli
  selector:
    app: zookeeper