// Code generated by go-swagger; DO NOT EDIT.

package request_feature_view_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	request_feature_view_model "github.com/feast-dev/feast/backend/api/go_http_client/request_feature_view_model"
)

// NewRequestFeatureViewServiceUpdateRequestFeatureViewParams creates a new RequestFeatureViewServiceUpdateRequestFeatureViewParams object
// with the default values initialized.
func NewRequestFeatureViewServiceUpdateRequestFeatureViewParams() *RequestFeatureViewServiceUpdateRequestFeatureViewParams {
	var ()
	return &RequestFeatureViewServiceUpdateRequestFeatureViewParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRequestFeatureViewServiceUpdateRequestFeatureViewParamsWithTimeout creates a new RequestFeatureViewServiceUpdateRequestFeatureViewParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRequestFeatureViewServiceUpdateRequestFeatureViewParamsWithTimeout(timeout time.Duration) *RequestFeatureViewServiceUpdateRequestFeatureViewParams {
	var ()
	return &RequestFeatureViewServiceUpdateRequestFeatureViewParams{

		timeout: timeout,
	}
}

// NewRequestFeatureViewServiceUpdateRequestFeatureViewParamsWithContext creates a new RequestFeatureViewServiceUpdateRequestFeatureViewParams object
// with the default values initialized, and the ability to set a context for a request
func NewRequestFeatureViewServiceUpdateRequestFeatureViewParamsWithContext(ctx context.Context) *RequestFeatureViewServiceUpdateRequestFeatureViewParams {
	var ()
	return &RequestFeatureViewServiceUpdateRequestFeatureViewParams{

		Context: ctx,
	}
}

// NewRequestFeatureViewServiceUpdateRequestFeatureViewParamsWithHTTPClient creates a new RequestFeatureViewServiceUpdateRequestFeatureViewParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRequestFeatureViewServiceUpdateRequestFeatureViewParamsWithHTTPClient(client *http.Client) *RequestFeatureViewServiceUpdateRequestFeatureViewParams {
	var ()
	return &RequestFeatureViewServiceUpdateRequestFeatureViewParams{
		HTTPClient: client,
	}
}

/*RequestFeatureViewServiceUpdateRequestFeatureViewParams contains all the parameters to send to the API endpoint
for the request feature view service update request feature view operation typically these are written to a http.Request
*/
type RequestFeatureViewServiceUpdateRequestFeatureViewParams struct {

	/*Body*/
	Body *request_feature_view_model.APIRequestFeatureView

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the request feature view service update request feature view params
func (o *RequestFeatureViewServiceUpdateRequestFeatureViewParams) WithTimeout(timeout time.Duration) *RequestFeatureViewServiceUpdateRequestFeatureViewParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the request feature view service update request feature view params
func (o *RequestFeatureViewServiceUpdateRequestFeatureViewParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the request feature view service update request feature view params
func (o *RequestFeatureViewServiceUpdateRequestFeatureViewParams) WithContext(ctx context.Context) *RequestFeatureViewServiceUpdateRequestFeatureViewParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the request feature view service update request feature view params
func (o *RequestFeatureViewServiceUpdateRequestFeatureViewParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the request feature view service update request feature view params
func (o *RequestFeatureViewServiceUpdateRequestFeatureViewParams) WithHTTPClient(client *http.Client) *RequestFeatureViewServiceUpdateRequestFeatureViewParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the request feature view service update request feature view params
func (o *RequestFeatureViewServiceUpdateRequestFeatureViewParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the request feature view service update request feature view params
func (o *RequestFeatureViewServiceUpdateRequestFeatureViewParams) WithBody(body *request_feature_view_model.APIRequestFeatureView) *RequestFeatureViewServiceUpdateRequestFeatureViewParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the request feature view service update request feature view params
func (o *RequestFeatureViewServiceUpdateRequestFeatureViewParams) SetBody(body *request_feature_view_model.APIRequestFeatureView) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RequestFeatureViewServiceUpdateRequestFeatureViewParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
