// Code generated by go-swagger; DO NOT EDIT.

package request_feature_view_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	request_feature_view_model "github.com/feast-dev/feast/backend/api/go_http_client/request_feature_view_model"
)

// RequestFeatureViewServiceGetRequestFeatureViewReader is a Reader for the RequestFeatureViewServiceGetRequestFeatureView structure.
type RequestFeatureViewServiceGetRequestFeatureViewReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RequestFeatureViewServiceGetRequestFeatureViewReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewRequestFeatureViewServiceGetRequestFeatureViewOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewRequestFeatureViewServiceGetRequestFeatureViewDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRequestFeatureViewServiceGetRequestFeatureViewOK creates a RequestFeatureViewServiceGetRequestFeatureViewOK with default headers values
func NewRequestFeatureViewServiceGetRequestFeatureViewOK() *RequestFeatureViewServiceGetRequestFeatureViewOK {
	return &RequestFeatureViewServiceGetRequestFeatureViewOK{}
}

/*RequestFeatureViewServiceGetRequestFeatureViewOK handles this case with default header values.

A successful response.
*/
type RequestFeatureViewServiceGetRequestFeatureViewOK struct {
	Payload *request_feature_view_model.APIRequestFeatureView
}

func (o *RequestFeatureViewServiceGetRequestFeatureViewOK) Error() string {
	return fmt.Sprintf("[GET /GetRequestFeatureView][%d] requestFeatureViewServiceGetRequestFeatureViewOK  %+v", 200, o.Payload)
}

func (o *RequestFeatureViewServiceGetRequestFeatureViewOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(request_feature_view_model.APIRequestFeatureView)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRequestFeatureViewServiceGetRequestFeatureViewDefault creates a RequestFeatureViewServiceGetRequestFeatureViewDefault with default headers values
func NewRequestFeatureViewServiceGetRequestFeatureViewDefault(code int) *RequestFeatureViewServiceGetRequestFeatureViewDefault {
	return &RequestFeatureViewServiceGetRequestFeatureViewDefault{
		_statusCode: code,
	}
}

/*RequestFeatureViewServiceGetRequestFeatureViewDefault handles this case with default header values.

An unexpected error response.
*/
type RequestFeatureViewServiceGetRequestFeatureViewDefault struct {
	_statusCode int

	Payload *request_feature_view_model.GatewayruntimeError
}

// Code gets the status code for the request feature view service get request feature view default response
func (o *RequestFeatureViewServiceGetRequestFeatureViewDefault) Code() int {
	return o._statusCode
}

func (o *RequestFeatureViewServiceGetRequestFeatureViewDefault) Error() string {
	return fmt.Sprintf("[GET /GetRequestFeatureView][%d] RequestFeatureViewService_GetRequestFeatureView default  %+v", o._statusCode, o.Payload)
}

func (o *RequestFeatureViewServiceGetRequestFeatureViewDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(request_feature_view_model.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
