// Code generated by go-swagger; DO NOT EDIT.

package request_feature_view_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	request_feature_view_model "github.com/feast-dev/feast/backend/api/go_http_client/request_feature_view_model"
)

// RequestFeatureViewServiceListRequestFeatureViewsReader is a Reader for the RequestFeatureViewServiceListRequestFeatureViews structure.
type RequestFeatureViewServiceListRequestFeatureViewsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RequestFeatureViewServiceListRequestFeatureViewsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewRequestFeatureViewServiceListRequestFeatureViewsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewRequestFeatureViewServiceListRequestFeatureViewsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRequestFeatureViewServiceListRequestFeatureViewsOK creates a RequestFeatureViewServiceListRequestFeatureViewsOK with default headers values
func NewRequestFeatureViewServiceListRequestFeatureViewsOK() *RequestFeatureViewServiceListRequestFeatureViewsOK {
	return &RequestFeatureViewServiceListRequestFeatureViewsOK{}
}

/*RequestFeatureViewServiceListRequestFeatureViewsOK handles this case with default header values.

A successful response.
*/
type RequestFeatureViewServiceListRequestFeatureViewsOK struct {
	Payload *request_feature_view_model.APIListRequestFeatureViewsResponse
}

func (o *RequestFeatureViewServiceListRequestFeatureViewsOK) Error() string {
	return fmt.Sprintf("[GET /ListRequestFeatureViews][%d] requestFeatureViewServiceListRequestFeatureViewsOK  %+v", 200, o.Payload)
}

func (o *RequestFeatureViewServiceListRequestFeatureViewsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(request_feature_view_model.APIListRequestFeatureViewsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRequestFeatureViewServiceListRequestFeatureViewsDefault creates a RequestFeatureViewServiceListRequestFeatureViewsDefault with default headers values
func NewRequestFeatureViewServiceListRequestFeatureViewsDefault(code int) *RequestFeatureViewServiceListRequestFeatureViewsDefault {
	return &RequestFeatureViewServiceListRequestFeatureViewsDefault{
		_statusCode: code,
	}
}

/*RequestFeatureViewServiceListRequestFeatureViewsDefault handles this case with default header values.

An unexpected error response.
*/
type RequestFeatureViewServiceListRequestFeatureViewsDefault struct {
	_statusCode int

	Payload *request_feature_view_model.GatewayruntimeError
}

// Code gets the status code for the request feature view service list request feature views default response
func (o *RequestFeatureViewServiceListRequestFeatureViewsDefault) Code() int {
	return o._statusCode
}

func (o *RequestFeatureViewServiceListRequestFeatureViewsDefault) Error() string {
	return fmt.Sprintf("[GET /ListRequestFeatureViews][%d] RequestFeatureViewService_ListRequestFeatureViews default  %+v", o._statusCode, o.Payload)
}

func (o *RequestFeatureViewServiceListRequestFeatureViewsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(request_feature_view_model.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
