// Code generated by go-swagger; DO NOT EDIT.

package request_feature_view_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	request_feature_view_model "github.com/feast-dev/feast/backend/api/go_http_client/request_feature_view_model"
)

// RequestFeatureViewServiceDeleteRequestFeatureViewReader is a Reader for the RequestFeatureViewServiceDeleteRequestFeatureView structure.
type RequestFeatureViewServiceDeleteRequestFeatureViewReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RequestFeatureViewServiceDeleteRequestFeatureViewReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewRequestFeatureViewServiceDeleteRequestFeatureViewOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewRequestFeatureViewServiceDeleteRequestFeatureViewDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRequestFeatureViewServiceDeleteRequestFeatureViewOK creates a RequestFeatureViewServiceDeleteRequestFeatureViewOK with default headers values
func NewRequestFeatureViewServiceDeleteRequestFeatureViewOK() *RequestFeatureViewServiceDeleteRequestFeatureViewOK {
	return &RequestFeatureViewServiceDeleteRequestFeatureViewOK{}
}

/*RequestFeatureViewServiceDeleteRequestFeatureViewOK handles this case with default header values.

A successful response.
*/
type RequestFeatureViewServiceDeleteRequestFeatureViewOK struct {
	Payload interface{}
}

func (o *RequestFeatureViewServiceDeleteRequestFeatureViewOK) Error() string {
	return fmt.Sprintf("[DELETE /DeleteRequestFeatureView][%d] requestFeatureViewServiceDeleteRequestFeatureViewOK  %+v", 200, o.Payload)
}

func (o *RequestFeatureViewServiceDeleteRequestFeatureViewOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRequestFeatureViewServiceDeleteRequestFeatureViewDefault creates a RequestFeatureViewServiceDeleteRequestFeatureViewDefault with default headers values
func NewRequestFeatureViewServiceDeleteRequestFeatureViewDefault(code int) *RequestFeatureViewServiceDeleteRequestFeatureViewDefault {
	return &RequestFeatureViewServiceDeleteRequestFeatureViewDefault{
		_statusCode: code,
	}
}

/*RequestFeatureViewServiceDeleteRequestFeatureViewDefault handles this case with default header values.

An unexpected error response.
*/
type RequestFeatureViewServiceDeleteRequestFeatureViewDefault struct {
	_statusCode int

	Payload *request_feature_view_model.GatewayruntimeError
}

// Code gets the status code for the request feature view service delete request feature view default response
func (o *RequestFeatureViewServiceDeleteRequestFeatureViewDefault) Code() int {
	return o._statusCode
}

func (o *RequestFeatureViewServiceDeleteRequestFeatureViewDefault) Error() string {
	return fmt.Sprintf("[DELETE /DeleteRequestFeatureView][%d] RequestFeatureViewService_DeleteRequestFeatureView default  %+v", o._statusCode, o.Payload)
}

func (o *RequestFeatureViewServiceDeleteRequestFeatureViewDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(request_feature_view_model.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
