// Code generated by go-swagger; DO NOT EDIT.

package request_feature_view_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRequestFeatureViewServiceListRequestFeatureViewsParams creates a new RequestFeatureViewServiceListRequestFeatureViewsParams object
// with the default values initialized.
func NewRequestFeatureViewServiceListRequestFeatureViewsParams() *RequestFeatureViewServiceListRequestFeatureViewsParams {
	var ()
	return &RequestFeatureViewServiceListRequestFeatureViewsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRequestFeatureViewServiceListRequestFeatureViewsParamsWithTimeout creates a new RequestFeatureViewServiceListRequestFeatureViewsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRequestFeatureViewServiceListRequestFeatureViewsParamsWithTimeout(timeout time.Duration) *RequestFeatureViewServiceListRequestFeatureViewsParams {
	var ()
	return &RequestFeatureViewServiceListRequestFeatureViewsParams{

		timeout: timeout,
	}
}

// NewRequestFeatureViewServiceListRequestFeatureViewsParamsWithContext creates a new RequestFeatureViewServiceListRequestFeatureViewsParams object
// with the default values initialized, and the ability to set a context for a request
func NewRequestFeatureViewServiceListRequestFeatureViewsParamsWithContext(ctx context.Context) *RequestFeatureViewServiceListRequestFeatureViewsParams {
	var ()
	return &RequestFeatureViewServiceListRequestFeatureViewsParams{

		Context: ctx,
	}
}

// NewRequestFeatureViewServiceListRequestFeatureViewsParamsWithHTTPClient creates a new RequestFeatureViewServiceListRequestFeatureViewsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRequestFeatureViewServiceListRequestFeatureViewsParamsWithHTTPClient(client *http.Client) *RequestFeatureViewServiceListRequestFeatureViewsParams {
	var ()
	return &RequestFeatureViewServiceListRequestFeatureViewsParams{
		HTTPClient: client,
	}
}

/*RequestFeatureViewServiceListRequestFeatureViewsParams contains all the parameters to send to the API endpoint
for the request feature view service list request feature views operation typically these are written to a http.Request
*/
type RequestFeatureViewServiceListRequestFeatureViewsParams struct {

	/*Project*/
	Project *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the request feature view service list request feature views params
func (o *RequestFeatureViewServiceListRequestFeatureViewsParams) WithTimeout(timeout time.Duration) *RequestFeatureViewServiceListRequestFeatureViewsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the request feature view service list request feature views params
func (o *RequestFeatureViewServiceListRequestFeatureViewsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the request feature view service list request feature views params
func (o *RequestFeatureViewServiceListRequestFeatureViewsParams) WithContext(ctx context.Context) *RequestFeatureViewServiceListRequestFeatureViewsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the request feature view service list request feature views params
func (o *RequestFeatureViewServiceListRequestFeatureViewsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the request feature view service list request feature views params
func (o *RequestFeatureViewServiceListRequestFeatureViewsParams) WithHTTPClient(client *http.Client) *RequestFeatureViewServiceListRequestFeatureViewsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the request feature view service list request feature views params
func (o *RequestFeatureViewServiceListRequestFeatureViewsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProject adds the project to the request feature view service list request feature views params
func (o *RequestFeatureViewServiceListRequestFeatureViewsParams) WithProject(project *string) *RequestFeatureViewServiceListRequestFeatureViewsParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the request feature view service list request feature views params
func (o *RequestFeatureViewServiceListRequestFeatureViewsParams) SetProject(project *string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *RequestFeatureViewServiceListRequestFeatureViewsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Project != nil {

		// query param project
		var qrProject string
		if o.Project != nil {
			qrProject = *o.Project
		}
		qProject := qrProject
		if qProject != "" {
			if err := r.SetQueryParam("project", qProject); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
