# coding: utf-8

"""
    Feast Registry API

    This file contains REST API specification for Feast Registry. The file is autogenerated from the swagger definition.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import frs_api
from frs_api.models.api_list_feature_views_response import ApiListFeatureViewsResponse  # noqa: E501
from frs_api.rest import ApiException

class TestApiListFeatureViewsResponse(unittest.TestCase):
    """ApiListFeatureViewsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ApiListFeatureViewsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = frs_api.models.api_list_feature_views_response.ApiListFeatureViewsResponse()  # noqa: E501
        if include_optional :
            return ApiListFeatureViewsResponse(
                feature_views = [
                    frs_api.models.api_feature_view.apiFeatureView(
                        name = '0', 
                        project = '0', 
                        entities = [
                            '0'
                            ], 
                        features = [
                            frs_api.models.api_feature.apiFeature(
                                name = '0', 
                                value_type = 'INVALID', 
                                tags = {
                                    'key' : '0'
                                    }, )
                            ], 
                        description = '0', 
                        tags = {
                            'key' : '0'
                            }, 
                        owner = '0', 
                        ttl = '0', 
                        batch_source = '0', 
                        stream_source = '0', 
                        online = True, 
                        created_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_updated_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        materialization_intervals = [
                            frs_api.models.api_materialization_interval.apiMaterializationInterval(
                                start_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                end_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                            ], )
                    ]
            )
        else :
            return ApiListFeatureViewsResponse(
        )

    def testApiListFeatureViewsResponse(self):
        """Test ApiListFeatureViewsResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
