# coding: utf-8

"""
    Feast Registry API

    This file contains REST API specification for Feast Registry. The file is autogenerated from the swagger definition.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import frs_api
from frs_api.api.entity_service_api import EntityServiceApi  # noqa: E501
from frs_api.rest import ApiException


class TestEntityServiceApi(unittest.TestCase):
    """EntityServiceApi unit test stubs"""

    def setUp(self):
        self.api = frs_api.api.entity_service_api.EntityServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_entity_service_create_entity(self):
        """Test case for entity_service_create_entity

        """
        pass

    def test_entity_service_delete_entity(self):
        """Test case for entity_service_delete_entity

        """
        pass

    def test_entity_service_get_entity(self):
        """Test case for entity_service_get_entity

        """
        pass

    def test_entity_service_list_entities(self):
        """Test case for entity_service_list_entities

        """
        pass

    def test_entity_service_update_entity(self):
        """Test case for entity_service_update_entity

        """
        pass


if __name__ == '__main__':
    unittest.main()
