# coding: utf-8

"""
    Feast Registry API

    This file contains REST API specification for Feast Registry. The file is autogenerated from the swagger definition.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import frs_api
from frs_api.models.api_list_entities_response import ApiListEntitiesResponse  # noqa: E501
from frs_api.rest import ApiException

class TestApiListEntitiesResponse(unittest.TestCase):
    """ApiListEntitiesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ApiListEntitiesResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = frs_api.models.api_list_entities_response.ApiListEntitiesResponse()  # noqa: E501
        if include_optional :
            return ApiListEntitiesResponse(
                entities = [
                    frs_api.models.api_entity.apiEntity(
                        name = '0', 
                        project = '0', 
                        value_type = 'INVALID', 
                        description = '0', 
                        join_key = '0', 
                        tags = {
                            'key' : '0'
                            }, 
                        owner = '0', 
                        created_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_updated_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else :
            return ApiListEntitiesResponse(
        )

    def testApiListEntitiesResponse(self):
        """Test ApiListEntitiesResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
