# coding: utf-8

"""
    Feast Registry API

    This file contains REST API specification for Feast Registry. The file is autogenerated from the swagger definition.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import frs_api
from frs_api.models.api_infra_objects import ApiInfraObjects  # noqa: E501
from frs_api.rest import ApiException

class TestApiInfraObjects(unittest.TestCase):
    """ApiInfraObjects unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ApiInfraObjects
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = frs_api.models.api_infra_objects.ApiInfraObjects()  # noqa: E501
        if include_optional :
            return ApiInfraObjects(
                objects = [
                    frs_api.models.api_infra_object.apiInfraObject(
                        infra_object_class_type = '0', 
                        infra_object = '0', )
                    ]
            )
        else :
            return ApiInfraObjects(
        )

    def testApiInfraObjects(self):
        """Test ApiInfraObjects"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
