# coding: utf-8

"""
    Feast Registry API

    This file contains REST API specification for Feast Registry. The file is autogenerated from the swagger definition.  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import frs_api
from frs_api.api.feature_service_service_api import FeatureServiceServiceApi  # noqa: E501
from frs_api.rest import ApiException


class TestFeatureServiceServiceApi(unittest.TestCase):
    """FeatureServiceServiceApi unit test stubs"""

    def setUp(self):
        self.api = frs_api.api.feature_service_service_api.FeatureServiceServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_feature_service_service_create_feature_service(self):
        """Test case for feature_service_service_create_feature_service

        """
        pass

    def test_feature_service_service_delete_feature_service(self):
        """Test case for feature_service_service_delete_feature_service

        """
        pass

    def test_feature_service_service_get_feature_service(self):
        """Test case for feature_service_service_get_feature_service

        """
        pass

    def test_feature_service_service_list_feature_services(self):
        """Test case for feature_service_service_list_feature_services

        """
        pass

    def test_feature_service_service_update_feature_service(self):
        """Test case for feature_service_service_update_feature_service

        """
        pass


if __name__ == '__main__':
    unittest.main()
