// Code generated by go-swagger; DO NOT EDIT.

package feature_view_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIFeatureView api feature view
// swagger:model apiFeatureView
type APIFeatureView struct {

	// Batch/Offline DataSource where this view can retrieve offline feature data.
	// Protobuf object transformed to a JSON string.
	BatchSource string `json:"batch_source,omitempty"`

	// Creation time of the feature view.
	// Format: date-time
	CreatedTimestamp strfmt.DateTime `json:"created_timestamp,omitempty"`

	// Description of the feature view.
	Description string `json:"description,omitempty"`

	// List names of entities to associate with the features defined in this feature view. Not updatable.
	Entities []string `json:"entities"`

	// List of specifications for each field defined as part of this feature view.
	Features []*APIFeature `json:"features"`

	// Last update time of the feature view.
	// Format: date-time
	LastUpdatedTimestamp strfmt.DateTime `json:"last_updated_timestamp,omitempty"`

	// List of pairs (start_time, end_time) for which this feature view has been materialized.
	MaterializationIntervals []*APIMaterializationInterval `json:"materialization_intervals"`

	// Name of the feature view. Must be unique. Not updated.
	Name string `json:"name,omitempty"`

	// Whether these features should be served online or not.
	Online bool `json:"online,omitempty"`

	// Owner of the feature view.
	Owner string `json:"owner,omitempty"`

	// Name of Feast project that this feature view belongs to.
	Project string `json:"project,omitempty"`

	// Streaming DataSource from where this view can consume "online" feature data.
	// Protobuf object transformed to a JSON string.
	StreamSource string `json:"stream_source,omitempty"`

	// User defined metadata.
	Tags map[string]string `json:"tags,omitempty"`

	// Features in this feature view can only be retrieved from online serving younger than ttl.
	// Ttl is measured as the duration of time between the feature's event timestamp and when the feature is retrieved.
	// Feature values outside ttl will be returned as unset values and indicated to end user.
	TTL string `json:"ttl,omitempty"`
}

// Validate validates this api feature view
func (m *APIFeatureView) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedTimestamp(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFeatures(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastUpdatedTimestamp(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMaterializationIntervals(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIFeatureView) validateCreatedTimestamp(formats strfmt.Registry) error {

	if swag.IsZero(m.CreatedTimestamp) { // not required
		return nil
	}

	if err := validate.FormatOf("created_timestamp", "body", "date-time", m.CreatedTimestamp.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *APIFeatureView) validateFeatures(formats strfmt.Registry) error {

	if swag.IsZero(m.Features) { // not required
		return nil
	}

	for i := 0; i < len(m.Features); i++ {
		if swag.IsZero(m.Features[i]) { // not required
			continue
		}

		if m.Features[i] != nil {
			if err := m.Features[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("features" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *APIFeatureView) validateLastUpdatedTimestamp(formats strfmt.Registry) error {

	if swag.IsZero(m.LastUpdatedTimestamp) { // not required
		return nil
	}

	if err := validate.FormatOf("last_updated_timestamp", "body", "date-time", m.LastUpdatedTimestamp.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *APIFeatureView) validateMaterializationIntervals(formats strfmt.Registry) error {

	if swag.IsZero(m.MaterializationIntervals) { // not required
		return nil
	}

	for i := 0; i < len(m.MaterializationIntervals); i++ {
		if swag.IsZero(m.MaterializationIntervals[i]) { // not required
			continue
		}

		if m.MaterializationIntervals[i] != nil {
			if err := m.MaterializationIntervals[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("materialization_intervals" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIFeatureView) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIFeatureView) UnmarshalBinary(b []byte) error {
	var res APIFeatureView
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
