// Code generated by go-swagger; DO NOT EDIT.

package infra_object_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewInfraObjectServiceListInfraObjectsParams creates a new InfraObjectServiceListInfraObjectsParams object
// with the default values initialized.
func NewInfraObjectServiceListInfraObjectsParams() *InfraObjectServiceListInfraObjectsParams {
	var ()
	return &InfraObjectServiceListInfraObjectsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewInfraObjectServiceListInfraObjectsParamsWithTimeout creates a new InfraObjectServiceListInfraObjectsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewInfraObjectServiceListInfraObjectsParamsWithTimeout(timeout time.Duration) *InfraObjectServiceListInfraObjectsParams {
	var ()
	return &InfraObjectServiceListInfraObjectsParams{

		timeout: timeout,
	}
}

// NewInfraObjectServiceListInfraObjectsParamsWithContext creates a new InfraObjectServiceListInfraObjectsParams object
// with the default values initialized, and the ability to set a context for a request
func NewInfraObjectServiceListInfraObjectsParamsWithContext(ctx context.Context) *InfraObjectServiceListInfraObjectsParams {
	var ()
	return &InfraObjectServiceListInfraObjectsParams{

		Context: ctx,
	}
}

// NewInfraObjectServiceListInfraObjectsParamsWithHTTPClient creates a new InfraObjectServiceListInfraObjectsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewInfraObjectServiceListInfraObjectsParamsWithHTTPClient(client *http.Client) *InfraObjectServiceListInfraObjectsParams {
	var ()
	return &InfraObjectServiceListInfraObjectsParams{
		HTTPClient: client,
	}
}

/*InfraObjectServiceListInfraObjectsParams contains all the parameters to send to the API endpoint
for the infra object service list infra objects operation typically these are written to a http.Request
*/
type InfraObjectServiceListInfraObjectsParams struct {

	/*Project*/
	Project *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the infra object service list infra objects params
func (o *InfraObjectServiceListInfraObjectsParams) WithTimeout(timeout time.Duration) *InfraObjectServiceListInfraObjectsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the infra object service list infra objects params
func (o *InfraObjectServiceListInfraObjectsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the infra object service list infra objects params
func (o *InfraObjectServiceListInfraObjectsParams) WithContext(ctx context.Context) *InfraObjectServiceListInfraObjectsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the infra object service list infra objects params
func (o *InfraObjectServiceListInfraObjectsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the infra object service list infra objects params
func (o *InfraObjectServiceListInfraObjectsParams) WithHTTPClient(client *http.Client) *InfraObjectServiceListInfraObjectsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the infra object service list infra objects params
func (o *InfraObjectServiceListInfraObjectsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProject adds the project to the infra object service list infra objects params
func (o *InfraObjectServiceListInfraObjectsParams) WithProject(project *string) *InfraObjectServiceListInfraObjectsParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the infra object service list infra objects params
func (o *InfraObjectServiceListInfraObjectsParams) SetProject(project *string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *InfraObjectServiceListInfraObjectsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Project != nil {

		// query param project
		var qrProject string
		if o.Project != nil {
			qrProject = *o.Project
		}
		qProject := qrProject
		if qProject != "" {
			if err := r.SetQueryParam("project", qProject); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
