// Code generated by go-swagger; DO NOT EDIT.

package request_feature_view_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// APIListRequestFeatureViewsResponse api list request feature views response
// swagger:model apiListRequestFeatureViewsResponse
type APIListRequestFeatureViewsResponse struct {

	// request feature views
	RequestFeatureViews []*APIRequestFeatureView `json:"request_feature_views"`
}

// Validate validates this api list request feature views response
func (m *APIListRequestFeatureViewsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRequestFeatureViews(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIListRequestFeatureViewsResponse) validateRequestFeatureViews(formats strfmt.Registry) error {

	if swag.IsZero(m.RequestFeatureViews) { // not required
		return nil
	}

	for i := 0; i < len(m.RequestFeatureViews); i++ {
		if swag.IsZero(m.RequestFeatureViews[i]) { // not required
			continue
		}

		if m.RequestFeatureViews[i] != nil {
			if err := m.RequestFeatureViews[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("request_feature_views" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIListRequestFeatureViewsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIListRequestFeatureViewsResponse) UnmarshalBinary(b []byte) error {
	var res APIListRequestFeatureViewsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
