// Code generated by go-swagger; DO NOT EDIT.

package entity_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	entity_model "github.com/feast-dev/feast/backend/api/go_http_client/entity_model"
)

// EntityServiceUpdateEntityReader is a Reader for the EntityServiceUpdateEntity structure.
type EntityServiceUpdateEntityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EntityServiceUpdateEntityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEntityServiceUpdateEntityOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewEntityServiceUpdateEntityDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEntityServiceUpdateEntityOK creates a EntityServiceUpdateEntityOK with default headers values
func NewEntityServiceUpdateEntityOK() *EntityServiceUpdateEntityOK {
	return &EntityServiceUpdateEntityOK{}
}

/*EntityServiceUpdateEntityOK handles this case with default header values.

A successful response.
*/
type EntityServiceUpdateEntityOK struct {
	Payload *entity_model.APIEntity
}

func (o *EntityServiceUpdateEntityOK) Error() string {
	return fmt.Sprintf("[POST /UpdateEntity][%d] entityServiceUpdateEntityOK  %+v", 200, o.Payload)
}

func (o *EntityServiceUpdateEntityOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(entity_model.APIEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEntityServiceUpdateEntityDefault creates a EntityServiceUpdateEntityDefault with default headers values
func NewEntityServiceUpdateEntityDefault(code int) *EntityServiceUpdateEntityDefault {
	return &EntityServiceUpdateEntityDefault{
		_statusCode: code,
	}
}

/*EntityServiceUpdateEntityDefault handles this case with default header values.

An unexpected error response.
*/
type EntityServiceUpdateEntityDefault struct {
	_statusCode int

	Payload *entity_model.GatewayruntimeError
}

// Code gets the status code for the entity service update entity default response
func (o *EntityServiceUpdateEntityDefault) Code() int {
	return o._statusCode
}

func (o *EntityServiceUpdateEntityDefault) Error() string {
	return fmt.Sprintf("[POST /UpdateEntity][%d] EntityService_UpdateEntity default  %+v", o._statusCode, o.Payload)
}

func (o *EntityServiceUpdateEntityDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(entity_model.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
