// Code generated by go-swagger; DO NOT EDIT.

package entity_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	entity_model "github.com/feast-dev/feast/backend/api/go_http_client/entity_model"
)

// EntityServiceDeleteEntityReader is a Reader for the EntityServiceDeleteEntity structure.
type EntityServiceDeleteEntityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EntityServiceDeleteEntityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEntityServiceDeleteEntityOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewEntityServiceDeleteEntityDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEntityServiceDeleteEntityOK creates a EntityServiceDeleteEntityOK with default headers values
func NewEntityServiceDeleteEntityOK() *EntityServiceDeleteEntityOK {
	return &EntityServiceDeleteEntityOK{}
}

/*EntityServiceDeleteEntityOK handles this case with default header values.

A successful response.
*/
type EntityServiceDeleteEntityOK struct {
	Payload interface{}
}

func (o *EntityServiceDeleteEntityOK) Error() string {
	return fmt.Sprintf("[DELETE /DeleteEntity][%d] entityServiceDeleteEntityOK  %+v", 200, o.Payload)
}

func (o *EntityServiceDeleteEntityOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEntityServiceDeleteEntityDefault creates a EntityServiceDeleteEntityDefault with default headers values
func NewEntityServiceDeleteEntityDefault(code int) *EntityServiceDeleteEntityDefault {
	return &EntityServiceDeleteEntityDefault{
		_statusCode: code,
	}
}

/*EntityServiceDeleteEntityDefault handles this case with default header values.

An unexpected error response.
*/
type EntityServiceDeleteEntityDefault struct {
	_statusCode int

	Payload *entity_model.GatewayruntimeError
}

// Code gets the status code for the entity service delete entity default response
func (o *EntityServiceDeleteEntityDefault) Code() int {
	return o._statusCode
}

func (o *EntityServiceDeleteEntityDefault) Error() string {
	return fmt.Sprintf("[DELETE /DeleteEntity][%d] EntityService_DeleteEntity default  %+v", o._statusCode, o.Payload)
}

func (o *EntityServiceDeleteEntityDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(entity_model.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
