// Code generated by go-swagger; DO NOT EDIT.

package entity_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	entity_model "github.com/feast-dev/feast/backend/api/go_http_client/entity_model"
)

// EntityServiceListEntitiesReader is a Reader for the EntityServiceListEntities structure.
type EntityServiceListEntitiesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EntityServiceListEntitiesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEntityServiceListEntitiesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewEntityServiceListEntitiesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEntityServiceListEntitiesOK creates a EntityServiceListEntitiesOK with default headers values
func NewEntityServiceListEntitiesOK() *EntityServiceListEntitiesOK {
	return &EntityServiceListEntitiesOK{}
}

/*EntityServiceListEntitiesOK handles this case with default header values.

A successful response.
*/
type EntityServiceListEntitiesOK struct {
	Payload *entity_model.APIListEntitiesResponse
}

func (o *EntityServiceListEntitiesOK) Error() string {
	return fmt.Sprintf("[GET /ListEntities][%d] entityServiceListEntitiesOK  %+v", 200, o.Payload)
}

func (o *EntityServiceListEntitiesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(entity_model.APIListEntitiesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEntityServiceListEntitiesDefault creates a EntityServiceListEntitiesDefault with default headers values
func NewEntityServiceListEntitiesDefault(code int) *EntityServiceListEntitiesDefault {
	return &EntityServiceListEntitiesDefault{
		_statusCode: code,
	}
}

/*EntityServiceListEntitiesDefault handles this case with default header values.

An unexpected error response.
*/
type EntityServiceListEntitiesDefault struct {
	_statusCode int

	Payload *entity_model.GatewayruntimeError
}

// Code gets the status code for the entity service list entities default response
func (o *EntityServiceListEntitiesDefault) Code() int {
	return o._statusCode
}

func (o *EntityServiceListEntitiesDefault) Error() string {
	return fmt.Sprintf("[GET /ListEntities][%d] EntityService_ListEntities default  %+v", o._statusCode, o.Payload)
}

func (o *EntityServiceListEntitiesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(entity_model.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
