// Code generated by go-swagger; DO NOT EDIT.

package entity_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEntityServiceListEntitiesParams creates a new EntityServiceListEntitiesParams object
// with the default values initialized.
func NewEntityServiceListEntitiesParams() *EntityServiceListEntitiesParams {
	var ()
	return &EntityServiceListEntitiesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEntityServiceListEntitiesParamsWithTimeout creates a new EntityServiceListEntitiesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEntityServiceListEntitiesParamsWithTimeout(timeout time.Duration) *EntityServiceListEntitiesParams {
	var ()
	return &EntityServiceListEntitiesParams{

		timeout: timeout,
	}
}

// NewEntityServiceListEntitiesParamsWithContext creates a new EntityServiceListEntitiesParams object
// with the default values initialized, and the ability to set a context for a request
func NewEntityServiceListEntitiesParamsWithContext(ctx context.Context) *EntityServiceListEntitiesParams {
	var ()
	return &EntityServiceListEntitiesParams{

		Context: ctx,
	}
}

// NewEntityServiceListEntitiesParamsWithHTTPClient creates a new EntityServiceListEntitiesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEntityServiceListEntitiesParamsWithHTTPClient(client *http.Client) *EntityServiceListEntitiesParams {
	var ()
	return &EntityServiceListEntitiesParams{
		HTTPClient: client,
	}
}

/*EntityServiceListEntitiesParams contains all the parameters to send to the API endpoint
for the entity service list entities operation typically these are written to a http.Request
*/
type EntityServiceListEntitiesParams struct {

	/*Project*/
	Project *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the entity service list entities params
func (o *EntityServiceListEntitiesParams) WithTimeout(timeout time.Duration) *EntityServiceListEntitiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the entity service list entities params
func (o *EntityServiceListEntitiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the entity service list entities params
func (o *EntityServiceListEntitiesParams) WithContext(ctx context.Context) *EntityServiceListEntitiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the entity service list entities params
func (o *EntityServiceListEntitiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the entity service list entities params
func (o *EntityServiceListEntitiesParams) WithHTTPClient(client *http.Client) *EntityServiceListEntitiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the entity service list entities params
func (o *EntityServiceListEntitiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProject adds the project to the entity service list entities params
func (o *EntityServiceListEntitiesParams) WithProject(project *string) *EntityServiceListEntitiesParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the entity service list entities params
func (o *EntityServiceListEntitiesParams) SetProject(project *string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *EntityServiceListEntitiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Project != nil {

		// query param project
		var qrProject string
		if o.Project != nil {
			qrProject = *o.Project
		}
		qProject := qrProject
		if qProject != "" {
			if err := r.SetQueryParam("project", qProject); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
