// Code generated by go-swagger; DO NOT EDIT.

package entity_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	entity_model "github.com/feast-dev/feast/backend/api/go_http_client/entity_model"
)

// EntityServiceGetEntityReader is a Reader for the EntityServiceGetEntity structure.
type EntityServiceGetEntityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EntityServiceGetEntityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEntityServiceGetEntityOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewEntityServiceGetEntityDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEntityServiceGetEntityOK creates a EntityServiceGetEntityOK with default headers values
func NewEntityServiceGetEntityOK() *EntityServiceGetEntityOK {
	return &EntityServiceGetEntityOK{}
}

/*EntityServiceGetEntityOK handles this case with default header values.

A successful response.
*/
type EntityServiceGetEntityOK struct {
	Payload *entity_model.APIEntity
}

func (o *EntityServiceGetEntityOK) Error() string {
	return fmt.Sprintf("[GET /GetEntity][%d] entityServiceGetEntityOK  %+v", 200, o.Payload)
}

func (o *EntityServiceGetEntityOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(entity_model.APIEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEntityServiceGetEntityDefault creates a EntityServiceGetEntityDefault with default headers values
func NewEntityServiceGetEntityDefault(code int) *EntityServiceGetEntityDefault {
	return &EntityServiceGetEntityDefault{
		_statusCode: code,
	}
}

/*EntityServiceGetEntityDefault handles this case with default header values.

An unexpected error response.
*/
type EntityServiceGetEntityDefault struct {
	_statusCode int

	Payload *entity_model.GatewayruntimeError
}

// Code gets the status code for the entity service get entity default response
func (o *EntityServiceGetEntityDefault) Code() int {
	return o._statusCode
}

func (o *EntityServiceGetEntityDefault) Error() string {
	return fmt.Sprintf("[GET /GetEntity][%d] EntityService_GetEntity default  %+v", o._statusCode, o.Payload)
}

func (o *EntityServiceGetEntityDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(entity_model.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
