// Code generated by go-swagger; DO NOT EDIT.

package feature_service_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	feature_service_model "github.com/feast-dev/feast/backend/api/go_http_client/feature_service_model"
)

// FeatureServiceServiceCreateFeatureServiceReader is a Reader for the FeatureServiceServiceCreateFeatureService structure.
type FeatureServiceServiceCreateFeatureServiceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FeatureServiceServiceCreateFeatureServiceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewFeatureServiceServiceCreateFeatureServiceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewFeatureServiceServiceCreateFeatureServiceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewFeatureServiceServiceCreateFeatureServiceOK creates a FeatureServiceServiceCreateFeatureServiceOK with default headers values
func NewFeatureServiceServiceCreateFeatureServiceOK() *FeatureServiceServiceCreateFeatureServiceOK {
	return &FeatureServiceServiceCreateFeatureServiceOK{}
}

/*FeatureServiceServiceCreateFeatureServiceOK handles this case with default header values.

A successful response.
*/
type FeatureServiceServiceCreateFeatureServiceOK struct {
	Payload *feature_service_model.APIFeatureService
}

func (o *FeatureServiceServiceCreateFeatureServiceOK) Error() string {
	return fmt.Sprintf("[POST /CreateFeatureService][%d] featureServiceServiceCreateFeatureServiceOK  %+v", 200, o.Payload)
}

func (o *FeatureServiceServiceCreateFeatureServiceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(feature_service_model.APIFeatureService)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFeatureServiceServiceCreateFeatureServiceDefault creates a FeatureServiceServiceCreateFeatureServiceDefault with default headers values
func NewFeatureServiceServiceCreateFeatureServiceDefault(code int) *FeatureServiceServiceCreateFeatureServiceDefault {
	return &FeatureServiceServiceCreateFeatureServiceDefault{
		_statusCode: code,
	}
}

/*FeatureServiceServiceCreateFeatureServiceDefault handles this case with default header values.

An unexpected error response.
*/
type FeatureServiceServiceCreateFeatureServiceDefault struct {
	_statusCode int

	Payload *feature_service_model.GatewayruntimeError
}

// Code gets the status code for the feature service service create feature service default response
func (o *FeatureServiceServiceCreateFeatureServiceDefault) Code() int {
	return o._statusCode
}

func (o *FeatureServiceServiceCreateFeatureServiceDefault) Error() string {
	return fmt.Sprintf("[POST /CreateFeatureService][%d] FeatureServiceService_CreateFeatureService default  %+v", o._statusCode, o.Payload)
}

func (o *FeatureServiceServiceCreateFeatureServiceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(feature_service_model.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
