// Code generated by go-swagger; DO NOT EDIT.

package feature_service_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	feature_service_model "github.com/feast-dev/feast/backend/api/go_http_client/feature_service_model"
)

// FeatureServiceServiceDeleteFeatureServiceReader is a Reader for the FeatureServiceServiceDeleteFeatureService structure.
type FeatureServiceServiceDeleteFeatureServiceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FeatureServiceServiceDeleteFeatureServiceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewFeatureServiceServiceDeleteFeatureServiceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewFeatureServiceServiceDeleteFeatureServiceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewFeatureServiceServiceDeleteFeatureServiceOK creates a FeatureServiceServiceDeleteFeatureServiceOK with default headers values
func NewFeatureServiceServiceDeleteFeatureServiceOK() *FeatureServiceServiceDeleteFeatureServiceOK {
	return &FeatureServiceServiceDeleteFeatureServiceOK{}
}

/*FeatureServiceServiceDeleteFeatureServiceOK handles this case with default header values.

A successful response.
*/
type FeatureServiceServiceDeleteFeatureServiceOK struct {
	Payload interface{}
}

func (o *FeatureServiceServiceDeleteFeatureServiceOK) Error() string {
	return fmt.Sprintf("[DELETE /DeleteFeatureService][%d] featureServiceServiceDeleteFeatureServiceOK  %+v", 200, o.Payload)
}

func (o *FeatureServiceServiceDeleteFeatureServiceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFeatureServiceServiceDeleteFeatureServiceDefault creates a FeatureServiceServiceDeleteFeatureServiceDefault with default headers values
func NewFeatureServiceServiceDeleteFeatureServiceDefault(code int) *FeatureServiceServiceDeleteFeatureServiceDefault {
	return &FeatureServiceServiceDeleteFeatureServiceDefault{
		_statusCode: code,
	}
}

/*FeatureServiceServiceDeleteFeatureServiceDefault handles this case with default header values.

An unexpected error response.
*/
type FeatureServiceServiceDeleteFeatureServiceDefault struct {
	_statusCode int

	Payload *feature_service_model.GatewayruntimeError
}

// Code gets the status code for the feature service service delete feature service default response
func (o *FeatureServiceServiceDeleteFeatureServiceDefault) Code() int {
	return o._statusCode
}

func (o *FeatureServiceServiceDeleteFeatureServiceDefault) Error() string {
	return fmt.Sprintf("[DELETE /DeleteFeatureService][%d] FeatureServiceService_DeleteFeatureService default  %+v", o._statusCode, o.Payload)
}

func (o *FeatureServiceServiceDeleteFeatureServiceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(feature_service_model.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
