// Code generated by go-swagger; DO NOT EDIT.

package feature_service_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	feature_service_model "github.com/feast-dev/feast/backend/api/go_http_client/feature_service_model"
)

// NewFeatureServiceServiceCreateFeatureServiceParams creates a new FeatureServiceServiceCreateFeatureServiceParams object
// with the default values initialized.
func NewFeatureServiceServiceCreateFeatureServiceParams() *FeatureServiceServiceCreateFeatureServiceParams {
	var ()
	return &FeatureServiceServiceCreateFeatureServiceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFeatureServiceServiceCreateFeatureServiceParamsWithTimeout creates a new FeatureServiceServiceCreateFeatureServiceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFeatureServiceServiceCreateFeatureServiceParamsWithTimeout(timeout time.Duration) *FeatureServiceServiceCreateFeatureServiceParams {
	var ()
	return &FeatureServiceServiceCreateFeatureServiceParams{

		timeout: timeout,
	}
}

// NewFeatureServiceServiceCreateFeatureServiceParamsWithContext creates a new FeatureServiceServiceCreateFeatureServiceParams object
// with the default values initialized, and the ability to set a context for a request
func NewFeatureServiceServiceCreateFeatureServiceParamsWithContext(ctx context.Context) *FeatureServiceServiceCreateFeatureServiceParams {
	var ()
	return &FeatureServiceServiceCreateFeatureServiceParams{

		Context: ctx,
	}
}

// NewFeatureServiceServiceCreateFeatureServiceParamsWithHTTPClient creates a new FeatureServiceServiceCreateFeatureServiceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFeatureServiceServiceCreateFeatureServiceParamsWithHTTPClient(client *http.Client) *FeatureServiceServiceCreateFeatureServiceParams {
	var ()
	return &FeatureServiceServiceCreateFeatureServiceParams{
		HTTPClient: client,
	}
}

/*FeatureServiceServiceCreateFeatureServiceParams contains all the parameters to send to the API endpoint
for the feature service service create feature service operation typically these are written to a http.Request
*/
type FeatureServiceServiceCreateFeatureServiceParams struct {

	/*Body*/
	Body *feature_service_model.APIFeatureService

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the feature service service create feature service params
func (o *FeatureServiceServiceCreateFeatureServiceParams) WithTimeout(timeout time.Duration) *FeatureServiceServiceCreateFeatureServiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the feature service service create feature service params
func (o *FeatureServiceServiceCreateFeatureServiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the feature service service create feature service params
func (o *FeatureServiceServiceCreateFeatureServiceParams) WithContext(ctx context.Context) *FeatureServiceServiceCreateFeatureServiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the feature service service create feature service params
func (o *FeatureServiceServiceCreateFeatureServiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the feature service service create feature service params
func (o *FeatureServiceServiceCreateFeatureServiceParams) WithHTTPClient(client *http.Client) *FeatureServiceServiceCreateFeatureServiceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the feature service service create feature service params
func (o *FeatureServiceServiceCreateFeatureServiceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the feature service service create feature service params
func (o *FeatureServiceServiceCreateFeatureServiceParams) WithBody(body *feature_service_model.APIFeatureService) *FeatureServiceServiceCreateFeatureServiceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the feature service service create feature service params
func (o *FeatureServiceServiceCreateFeatureServiceParams) SetBody(body *feature_service_model.APIFeatureService) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *FeatureServiceServiceCreateFeatureServiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
