// Code generated by go-swagger; DO NOT EDIT.

package feature_service_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewFeatureServiceServiceDeleteFeatureServiceParams creates a new FeatureServiceServiceDeleteFeatureServiceParams object
// with the default values initialized.
func NewFeatureServiceServiceDeleteFeatureServiceParams() *FeatureServiceServiceDeleteFeatureServiceParams {
	var ()
	return &FeatureServiceServiceDeleteFeatureServiceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewFeatureServiceServiceDeleteFeatureServiceParamsWithTimeout creates a new FeatureServiceServiceDeleteFeatureServiceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewFeatureServiceServiceDeleteFeatureServiceParamsWithTimeout(timeout time.Duration) *FeatureServiceServiceDeleteFeatureServiceParams {
	var ()
	return &FeatureServiceServiceDeleteFeatureServiceParams{

		timeout: timeout,
	}
}

// NewFeatureServiceServiceDeleteFeatureServiceParamsWithContext creates a new FeatureServiceServiceDeleteFeatureServiceParams object
// with the default values initialized, and the ability to set a context for a request
func NewFeatureServiceServiceDeleteFeatureServiceParamsWithContext(ctx context.Context) *FeatureServiceServiceDeleteFeatureServiceParams {
	var ()
	return &FeatureServiceServiceDeleteFeatureServiceParams{

		Context: ctx,
	}
}

// NewFeatureServiceServiceDeleteFeatureServiceParamsWithHTTPClient creates a new FeatureServiceServiceDeleteFeatureServiceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFeatureServiceServiceDeleteFeatureServiceParamsWithHTTPClient(client *http.Client) *FeatureServiceServiceDeleteFeatureServiceParams {
	var ()
	return &FeatureServiceServiceDeleteFeatureServiceParams{
		HTTPClient: client,
	}
}

/*FeatureServiceServiceDeleteFeatureServiceParams contains all the parameters to send to the API endpoint
for the feature service service delete feature service operation typically these are written to a http.Request
*/
type FeatureServiceServiceDeleteFeatureServiceParams struct {

	/*Name*/
	Name *string
	/*Project*/
	Project *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the feature service service delete feature service params
func (o *FeatureServiceServiceDeleteFeatureServiceParams) WithTimeout(timeout time.Duration) *FeatureServiceServiceDeleteFeatureServiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the feature service service delete feature service params
func (o *FeatureServiceServiceDeleteFeatureServiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the feature service service delete feature service params
func (o *FeatureServiceServiceDeleteFeatureServiceParams) WithContext(ctx context.Context) *FeatureServiceServiceDeleteFeatureServiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the feature service service delete feature service params
func (o *FeatureServiceServiceDeleteFeatureServiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the feature service service delete feature service params
func (o *FeatureServiceServiceDeleteFeatureServiceParams) WithHTTPClient(client *http.Client) *FeatureServiceServiceDeleteFeatureServiceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the feature service service delete feature service params
func (o *FeatureServiceServiceDeleteFeatureServiceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the feature service service delete feature service params
func (o *FeatureServiceServiceDeleteFeatureServiceParams) WithName(name *string) *FeatureServiceServiceDeleteFeatureServiceParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the feature service service delete feature service params
func (o *FeatureServiceServiceDeleteFeatureServiceParams) SetName(name *string) {
	o.Name = name
}

// WithProject adds the project to the feature service service delete feature service params
func (o *FeatureServiceServiceDeleteFeatureServiceParams) WithProject(project *string) *FeatureServiceServiceDeleteFeatureServiceParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the feature service service delete feature service params
func (o *FeatureServiceServiceDeleteFeatureServiceParams) SetProject(project *string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *FeatureServiceServiceDeleteFeatureServiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.Project != nil {

		// query param project
		var qrProject string
		if o.Project != nil {
			qrProject = *o.Project
		}
		qProject := qrProject
		if qProject != "" {
			if err := r.SetQueryParam("project", qProject); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
