// Code generated by go-swagger; DO NOT EDIT.

package project_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	project_model "github.com/feast-dev/feast/backend/api/go_http_client/project_model"
)

// ProjectServiceCreateProjectReader is a Reader for the ProjectServiceCreateProject structure.
type ProjectServiceCreateProjectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectServiceCreateProjectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewProjectServiceCreateProjectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewProjectServiceCreateProjectDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewProjectServiceCreateProjectOK creates a ProjectServiceCreateProjectOK with default headers values
func NewProjectServiceCreateProjectOK() *ProjectServiceCreateProjectOK {
	return &ProjectServiceCreateProjectOK{}
}

/*ProjectServiceCreateProjectOK handles this case with default header values.

A successful response.
*/
type ProjectServiceCreateProjectOK struct {
	Payload *project_model.APIProject
}

func (o *ProjectServiceCreateProjectOK) Error() string {
	return fmt.Sprintf("[POST /CreateProject][%d] projectServiceCreateProjectOK  %+v", 200, o.Payload)
}

func (o *ProjectServiceCreateProjectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(project_model.APIProject)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProjectServiceCreateProjectDefault creates a ProjectServiceCreateProjectDefault with default headers values
func NewProjectServiceCreateProjectDefault(code int) *ProjectServiceCreateProjectDefault {
	return &ProjectServiceCreateProjectDefault{
		_statusCode: code,
	}
}

/*ProjectServiceCreateProjectDefault handles this case with default header values.

An unexpected error response.
*/
type ProjectServiceCreateProjectDefault struct {
	_statusCode int

	Payload *project_model.GatewayruntimeError
}

// Code gets the status code for the project service create project default response
func (o *ProjectServiceCreateProjectDefault) Code() int {
	return o._statusCode
}

func (o *ProjectServiceCreateProjectDefault) Error() string {
	return fmt.Sprintf("[POST /CreateProject][%d] ProjectService_CreateProject default  %+v", o._statusCode, o.Payload)
}

func (o *ProjectServiceCreateProjectDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(project_model.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
