// Code generated by go-swagger; DO NOT EDIT.

package project_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	project_model "github.com/feast-dev/feast/backend/api/go_http_client/project_model"
)

// ProjectServiceGetProjectReader is a Reader for the ProjectServiceGetProject structure.
type ProjectServiceGetProjectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ProjectServiceGetProjectReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewProjectServiceGetProjectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewProjectServiceGetProjectDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewProjectServiceGetProjectOK creates a ProjectServiceGetProjectOK with default headers values
func NewProjectServiceGetProjectOK() *ProjectServiceGetProjectOK {
	return &ProjectServiceGetProjectOK{}
}

/*ProjectServiceGetProjectOK handles this case with default header values.

A successful response.
*/
type ProjectServiceGetProjectOK struct {
	Payload *project_model.APIProject
}

func (o *ProjectServiceGetProjectOK) Error() string {
	return fmt.Sprintf("[GET /GetProject][%d] projectServiceGetProjectOK  %+v", 200, o.Payload)
}

func (o *ProjectServiceGetProjectOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(project_model.APIProject)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewProjectServiceGetProjectDefault creates a ProjectServiceGetProjectDefault with default headers values
func NewProjectServiceGetProjectDefault(code int) *ProjectServiceGetProjectDefault {
	return &ProjectServiceGetProjectDefault{
		_statusCode: code,
	}
}

/*ProjectServiceGetProjectDefault handles this case with default header values.

An unexpected error response.
*/
type ProjectServiceGetProjectDefault struct {
	_statusCode int

	Payload *project_model.GatewayruntimeError
}

// Code gets the status code for the project service get project default response
func (o *ProjectServiceGetProjectDefault) Code() int {
	return o._statusCode
}

func (o *ProjectServiceGetProjectDefault) Error() string {
	return fmt.Sprintf("[GET /GetProject][%d] ProjectService_GetProject default  %+v", o._statusCode, o.Payload)
}

func (o *ProjectServiceGetProjectDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(project_model.GatewayruntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
