// Code generated by go-swagger; DO NOT EDIT.

package data_source_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	data_source_model "github.com/feast-dev/feast/backend/api/go_http_client/data_source_model"
)

// NewDataSourceServiceCreateDataSourceParams creates a new DataSourceServiceCreateDataSourceParams object
// with the default values initialized.
func NewDataSourceServiceCreateDataSourceParams() *DataSourceServiceCreateDataSourceParams {
	var ()
	return &DataSourceServiceCreateDataSourceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDataSourceServiceCreateDataSourceParamsWithTimeout creates a new DataSourceServiceCreateDataSourceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDataSourceServiceCreateDataSourceParamsWithTimeout(timeout time.Duration) *DataSourceServiceCreateDataSourceParams {
	var ()
	return &DataSourceServiceCreateDataSourceParams{

		timeout: timeout,
	}
}

// NewDataSourceServiceCreateDataSourceParamsWithContext creates a new DataSourceServiceCreateDataSourceParams object
// with the default values initialized, and the ability to set a context for a request
func NewDataSourceServiceCreateDataSourceParamsWithContext(ctx context.Context) *DataSourceServiceCreateDataSourceParams {
	var ()
	return &DataSourceServiceCreateDataSourceParams{

		Context: ctx,
	}
}

// NewDataSourceServiceCreateDataSourceParamsWithHTTPClient creates a new DataSourceServiceCreateDataSourceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDataSourceServiceCreateDataSourceParamsWithHTTPClient(client *http.Client) *DataSourceServiceCreateDataSourceParams {
	var ()
	return &DataSourceServiceCreateDataSourceParams{
		HTTPClient: client,
	}
}

/*DataSourceServiceCreateDataSourceParams contains all the parameters to send to the API endpoint
for the data source service create data source operation typically these are written to a http.Request
*/
type DataSourceServiceCreateDataSourceParams struct {

	/*Body*/
	Body *data_source_model.APIDataSource

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the data source service create data source params
func (o *DataSourceServiceCreateDataSourceParams) WithTimeout(timeout time.Duration) *DataSourceServiceCreateDataSourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the data source service create data source params
func (o *DataSourceServiceCreateDataSourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the data source service create data source params
func (o *DataSourceServiceCreateDataSourceParams) WithContext(ctx context.Context) *DataSourceServiceCreateDataSourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the data source service create data source params
func (o *DataSourceServiceCreateDataSourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the data source service create data source params
func (o *DataSourceServiceCreateDataSourceParams) WithHTTPClient(client *http.Client) *DataSourceServiceCreateDataSourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the data source service create data source params
func (o *DataSourceServiceCreateDataSourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the data source service create data source params
func (o *DataSourceServiceCreateDataSourceParams) WithBody(body *data_source_model.APIDataSource) *DataSourceServiceCreateDataSourceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the data source service create data source params
func (o *DataSourceServiceCreateDataSourceParams) SetBody(body *data_source_model.APIDataSource) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DataSourceServiceCreateDataSourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
