// Code generated by go-swagger; DO NOT EDIT.

package data_source_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	data_source_model "github.com/feast-dev/feast/backend/api/go_http_client/data_source_model"
)

// NewDataSourceServiceUpdateDataSourceParams creates a new DataSourceServiceUpdateDataSourceParams object
// with the default values initialized.
func NewDataSourceServiceUpdateDataSourceParams() *DataSourceServiceUpdateDataSourceParams {
	var ()
	return &DataSourceServiceUpdateDataSourceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDataSourceServiceUpdateDataSourceParamsWithTimeout creates a new DataSourceServiceUpdateDataSourceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDataSourceServiceUpdateDataSourceParamsWithTimeout(timeout time.Duration) *DataSourceServiceUpdateDataSourceParams {
	var ()
	return &DataSourceServiceUpdateDataSourceParams{

		timeout: timeout,
	}
}

// NewDataSourceServiceUpdateDataSourceParamsWithContext creates a new DataSourceServiceUpdateDataSourceParams object
// with the default values initialized, and the ability to set a context for a request
func NewDataSourceServiceUpdateDataSourceParamsWithContext(ctx context.Context) *DataSourceServiceUpdateDataSourceParams {
	var ()
	return &DataSourceServiceUpdateDataSourceParams{

		Context: ctx,
	}
}

// NewDataSourceServiceUpdateDataSourceParamsWithHTTPClient creates a new DataSourceServiceUpdateDataSourceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDataSourceServiceUpdateDataSourceParamsWithHTTPClient(client *http.Client) *DataSourceServiceUpdateDataSourceParams {
	var ()
	return &DataSourceServiceUpdateDataSourceParams{
		HTTPClient: client,
	}
}

/*DataSourceServiceUpdateDataSourceParams contains all the parameters to send to the API endpoint
for the data source service update data source operation typically these are written to a http.Request
*/
type DataSourceServiceUpdateDataSourceParams struct {

	/*Body*/
	Body *data_source_model.APIDataSource

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the data source service update data source params
func (o *DataSourceServiceUpdateDataSourceParams) WithTimeout(timeout time.Duration) *DataSourceServiceUpdateDataSourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the data source service update data source params
func (o *DataSourceServiceUpdateDataSourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the data source service update data source params
func (o *DataSourceServiceUpdateDataSourceParams) WithContext(ctx context.Context) *DataSourceServiceUpdateDataSourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the data source service update data source params
func (o *DataSourceServiceUpdateDataSourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the data source service update data source params
func (o *DataSourceServiceUpdateDataSourceParams) WithHTTPClient(client *http.Client) *DataSourceServiceUpdateDataSourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the data source service update data source params
func (o *DataSourceServiceUpdateDataSourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the data source service update data source params
func (o *DataSourceServiceUpdateDataSourceParams) WithBody(body *data_source_model.APIDataSource) *DataSourceServiceUpdateDataSourceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the data source service update data source params
func (o *DataSourceServiceUpdateDataSourceParams) SetBody(body *data_source_model.APIDataSource) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *DataSourceServiceUpdateDataSourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
