// Code generated by go-swagger; DO NOT EDIT.

package data_source_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDataSourceServiceListDataSourcesParams creates a new DataSourceServiceListDataSourcesParams object
// with the default values initialized.
func NewDataSourceServiceListDataSourcesParams() *DataSourceServiceListDataSourcesParams {
	var ()
	return &DataSourceServiceListDataSourcesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDataSourceServiceListDataSourcesParamsWithTimeout creates a new DataSourceServiceListDataSourcesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDataSourceServiceListDataSourcesParamsWithTimeout(timeout time.Duration) *DataSourceServiceListDataSourcesParams {
	var ()
	return &DataSourceServiceListDataSourcesParams{

		timeout: timeout,
	}
}

// NewDataSourceServiceListDataSourcesParamsWithContext creates a new DataSourceServiceListDataSourcesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDataSourceServiceListDataSourcesParamsWithContext(ctx context.Context) *DataSourceServiceListDataSourcesParams {
	var ()
	return &DataSourceServiceListDataSourcesParams{

		Context: ctx,
	}
}

// NewDataSourceServiceListDataSourcesParamsWithHTTPClient creates a new DataSourceServiceListDataSourcesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDataSourceServiceListDataSourcesParamsWithHTTPClient(client *http.Client) *DataSourceServiceListDataSourcesParams {
	var ()
	return &DataSourceServiceListDataSourcesParams{
		HTTPClient: client,
	}
}

/*DataSourceServiceListDataSourcesParams contains all the parameters to send to the API endpoint
for the data source service list data sources operation typically these are written to a http.Request
*/
type DataSourceServiceListDataSourcesParams struct {

	/*Project*/
	Project *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the data source service list data sources params
func (o *DataSourceServiceListDataSourcesParams) WithTimeout(timeout time.Duration) *DataSourceServiceListDataSourcesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the data source service list data sources params
func (o *DataSourceServiceListDataSourcesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the data source service list data sources params
func (o *DataSourceServiceListDataSourcesParams) WithContext(ctx context.Context) *DataSourceServiceListDataSourcesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the data source service list data sources params
func (o *DataSourceServiceListDataSourcesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the data source service list data sources params
func (o *DataSourceServiceListDataSourcesParams) WithHTTPClient(client *http.Client) *DataSourceServiceListDataSourcesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the data source service list data sources params
func (o *DataSourceServiceListDataSourcesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProject adds the project to the data source service list data sources params
func (o *DataSourceServiceListDataSourcesParams) WithProject(project *string) *DataSourceServiceListDataSourcesParams {
	o.SetProject(project)
	return o
}

// SetProject adds the project to the data source service list data sources params
func (o *DataSourceServiceListDataSourcesParams) SetProject(project *string) {
	o.Project = project
}

// WriteToRequest writes these params to a swagger request
func (o *DataSourceServiceListDataSourcesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Project != nil {

		// query param project
		var qrProject string
		if o.Project != nil {
			qrProject = *o.Project
		}
		qProject := qrProject
		if qProject != "" {
			if err := r.SetQueryParam("project", qProject); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
