// Code generated by go-swagger; DO NOT EDIT.

package data_source_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// APIListDataSourcesResponse api list data sources response
// swagger:model apiListDataSourcesResponse
type APIListDataSourcesResponse struct {

	// data sources
	DataSources []*APIDataSource `json:"data_sources"`
}

// Validate validates this api list data sources response
func (m *APIListDataSourcesResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDataSources(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIListDataSourcesResponse) validateDataSources(formats strfmt.Registry) error {

	if swag.IsZero(m.DataSources) { // not required
		return nil
	}

	for i := 0; i < len(m.DataSources); i++ {
		if swag.IsZero(m.DataSources[i]) { // not required
			continue
		}

		if m.DataSources[i] != nil {
			if err := m.DataSources[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("data_sources" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIListDataSourcesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIListDataSourcesResponse) UnmarshalBinary(b []byte) error {
	var res APIListDataSourcesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
