// Code generated by go-swagger; DO NOT EDIT.

package on_demand_feature_view_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// APIListOnDemandFeatureViewsResponse api list on demand feature views response
// swagger:model apiListOnDemandFeatureViewsResponse
type APIListOnDemandFeatureViewsResponse struct {

	// on demand feature views
	OnDemandFeatureViews []*APIOnDemandFeatureView `json:"on_demand_feature_views"`
}

// Validate validates this api list on demand feature views response
func (m *APIListOnDemandFeatureViewsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateOnDemandFeatureViews(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIListOnDemandFeatureViewsResponse) validateOnDemandFeatureViews(formats strfmt.Registry) error {

	if swag.IsZero(m.OnDemandFeatureViews) { // not required
		return nil
	}

	for i := 0; i < len(m.OnDemandFeatureViews); i++ {
		if swag.IsZero(m.OnDemandFeatureViews[i]) { // not required
			continue
		}

		if m.OnDemandFeatureViews[i] != nil {
			if err := m.OnDemandFeatureViews[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("on_demand_feature_views" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIListOnDemandFeatureViewsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIListOnDemandFeatureViewsResponse) UnmarshalBinary(b []byte) error {
	var res APIListOnDemandFeatureViewsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
